ALTER PROC USP_TEC_399W_COMBO ( 
--DECLARE  
        @DIV_CD        NVARCHAR(10) = '01' 
       ,@PLANT_CD      NVARCHAR(10) = '1130'  
       ,@WC_CD         NVARCHAR(10) = '13GA' 
       ,@CODE_CD       NVARCHAR(10) = 'WC' 
) 
AS  
 
IF @CODE_CD = 'PLANT' 
BEGIN 
 
    SELECT A.PLANT_CD AS CODE, A.PLANT_NM AS NAME  
        FROM BA_PLANT A 
    WHERE A.DIV_CD = @DIV_CD  
END 
 
IF @CODE_CD = 'WC' 
BEGIN  
    SELECT A.WC_CD AS CODE, A.WC_NM AS NAME  
        FROM BA_WORK_CENTER A   
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND ISNULL(A.WC_NM,'') <> '' 
END 
 
IF @CODE_CD = 'LINE' 
BEGIN  
    SELECT A.LINE_CD AS CODE, A.LINE_NM AS NAME  
        FROM BA_LINE A  
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD  
END  
 