CREATE PROC USP_TEC_399W_BATCH_QUERY(

--)

--SELECT *FROM BA_SUB_CD WHERE MAIN_CD = 'BA209'
--DECLARE 
     @DIV_CD       NVARCHAR(10) = '01'
    ,@PLANT_CD     NVARCHAR(10) = '1130' 
    ,@WC_CD        NVARCHAR(10) = '13GA'
    ,@LINE_CD      NVARCHAR(10) = '13G01A' 
    ,@PROC_CD      NVARCHAR(10) = 'RI'
    ,@ITEM_TYPE    NVARCHAR(1)  = 'J'
)
AS 

DECLARE @REQ_DT NVARCHAR(7) = CONVERT(NVARCHAR(7), GETDATE(), 120)

SELECT A.REQ_DT, A.REQ_NO, A.PLAN_SEQ, A.BATCH_NO, A.ITEM_TYPE, A.PRNT_ITEM_CD, B.ITEM_NM, A.LOT_NO,  
A.ITEM_CD, C.ITEM_NM, A.REQ_QTY, A.USE_QTY, A.USE_FLG 
FROM FLEXMES.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
INNER JOIN V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.PRNT_ITEM_CD = B.ITEM_CD 
INNER JOIN V_ITEM C WITH (NOLOCK) ON A.PLANT_CD = C.PLANT_CD AND A.ITEM_CD = C.ITEM_CD 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
  AND A.REQ_DT = @REQ_DT 
  AND A.ITEM_TYPE = @ITEM_TYPE 
  AND ISNULL(A.CHG_RSN,'') = ''
ORDER BY A.PLAN_SEQ ASC, A.BATCH_NO ASC, A.REQ_NO ASC 