DECLARE 
     @DIV_CD       NVARCHAR(10) = '01'
    ,@PLANT_CD     NVARCHAR(10) = '1130' 
    ,@WC_CD        NVARCHAR(10) = '13GA'
    ,@LINE_CD      NVARCHAR(10) = '13G01A' 
    ,@PROC_CD      NVARCHAR(10) = 'RI'
    ,@ITEM_TYPE1   NVARCHAR(1)  = 'J'
    ,@ITEM_TYPE2   NVARCHAR(1)  = 'L'

DECLARE @BATCH_QTY1 NUMERIC(18,3) = '1600' 
       ,@BATCH_QTY2 NUMERIC(18,3) = '400'

-- 배정 리스트를 담읍시다. 

IF OBJECT_ID('TEMPDB..#TEC_399_BATCH1') IS NOT NULL 
BEGIN 
    DROP TABLE #TEC_399_BATCH1
END 

IF OBJECT_ID('TEMPDB..#TEC_399_BATCH2') IS NOT NULL 
BEGIN 
    DROP TABLE #TEC_399_BATCH2
END 

CREATE TABLE #TEC_399_BATCH1 
(
     IDX            INT   IDENTITY(1,1) 
    ,REQ_DT         NVARCHAR(7)
    ,REQ_NO         NVARCHAR(50) 
    ,PLAN_SEQ       INT 
    ,BATCH_NO       INT 
    ,ITEM_TYPE      NVARCHAR(1) 
    ,PRNT_ITEM_CD   NVARCHAR(50) 
    ,PRNT_ITEM_NM   NVARCHAR(100) 
    ,LOT_NO         NVARCHAR(100) 
    ,ITEM_CD        NVARCHAR(50) 
    ,ITEM_NM        NVARCHAR(100) 
    ,REQ_QTY        NUMERIC(18,3) 
    ,USE_QTY        NUMERIC(18,3)
    ,USE_FLG        NVARCHAR(1) 
)


CREATE TABLE #TEC_399_BATCH2
(
     IDX            INT   IDENTITY(1,1) 
    ,REQ_DT         NVARCHAR(7)
    ,REQ_NO         NVARCHAR(50) 
    ,PLAN_SEQ       INT 
    ,BATCH_NO       INT 
    ,ITEM_TYPE      NVARCHAR(1) 
    ,PRNT_ITEM_CD   NVARCHAR(50) 
    ,PRNT_ITEM_NM   NVARCHAR(100) 
    ,LOT_NO         NVARCHAR(100) 
    ,ITEM_CD        NVARCHAR(50) 
    ,ITEM_NM        NVARCHAR(100) 
    ,REQ_QTY        NUMERIC(18,3) 
    ,USE_QTY        NUMERIC(18,3)
    ,USE_FLG        NVARCHAR(1) 
)

-- BACK DATA 정리

DECLARE @REQ_DT NVARCHAR(7) = CONVERT(NVARCHAR(7), GETDATE(), 120)

INSERT INTO #TEC_399_BATCH1 
(
    REQ_DT,         REQ_NO,         PLAN_SEQ,     BATCH_NO,        ITEM_TYPE, 
    PRNT_ITEM_CD,   PRNT_ITEM_NM,   LOT_NO,       ITEM_CD,         ITEM_NM, 
    REQ_QTY,        USE_QTY,        USE_FLG
)
SELECT A.REQ_DT, A.REQ_NO, A.PLAN_SEQ, A.BATCH_NO, A.ITEM_TYPE, 
A.PRNT_ITEM_CD, B.ITEM_NM AS PRNT_ITEM_NM, A.LOT_NO,  
A.ITEM_CD, C.ITEM_NM, A.REQ_QTY, A.USE_QTY, A.USE_FLG 
FROM FLEXMES.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
INNER JOIN FLEXMES.DBO.V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.PRNT_ITEM_CD = B.ITEM_CD 
INNER JOIN FLEXMES.DBO.V_ITEM C WITH (NOLOCK) ON A.PLANT_CD = C.PLANT_CD AND A.ITEM_CD = C.ITEM_CD 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
  AND A.REQ_DT = @REQ_DT 
  AND A.ITEM_TYPE = @ITEM_TYPE1 
  AND ISNULL(A.CHG_RSN,'') = ''
ORDER BY A.PLAN_SEQ ASC, A.BATCH_NO ASC, A.REQ_NO ASC 


INSERT INTO #TEC_399_BATCH2
(
    REQ_DT,         REQ_NO,         PLAN_SEQ,     BATCH_NO,        ITEM_TYPE, 
    PRNT_ITEM_CD,   PRNT_ITEM_NM,   LOT_NO,       ITEM_CD,         ITEM_NM, 
    REQ_QTY,        USE_QTY,        USE_FLG
)
SELECT A.REQ_DT, A.REQ_NO, A.PLAN_SEQ, A.BATCH_NO, A.ITEM_TYPE, 
A.PRNT_ITEM_CD, B.ITEM_NM AS PRNT_ITEM_NM, A.LOT_NO,  
A.ITEM_CD, C.ITEM_NM, A.REQ_QTY, A.USE_QTY, A.USE_FLG 
FROM FLEXMES.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
INNER JOIN V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.PRNT_ITEM_CD = B.ITEM_CD 
INNER JOIN V_ITEM C WITH (NOLOCK) ON A.PLANT_CD = C.PLANT_CD AND A.ITEM_CD = C.ITEM_CD 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
  AND A.REQ_DT = @REQ_DT 
  AND A.ITEM_TYPE = @ITEM_TYPE2
  AND ISNULL(A.CHG_RSN,'') = ''
ORDER BY A.PLAN_SEQ ASC, A.BATCH_NO ASC, A.REQ_NO ASC 


SELECT REQ_NO, LOT_NO, REQ_QTY
FROM #TEC_399_BATCH1
ORDER BY REQ_NO;
SELECT REQ_NO, LOT_NO, REQ_QTY
FROM #TEC_399_BATCH2
ORDER BY REQ_NO;

/*
-- 전구체 선입선출을 진행하자. 
SELECT Z.IDX, Z.REQ_NO, Z.LOT_NO, Z.REQ_QTY, Z.SUMQTY,                                       
CASE WHEN (@BATCH_QTY1 - Z.SUMQTY) >= 0 THEN (Z.REQ_QTY * -1)                                       
ELSE (Z.SUMQTY - @BATCH_QTY1) - Z.REQ_QTY   END  AS QTY                                        

FROM (                                       
SELECT Q.IDX, Q.REQ_NO, Q.LOT_NO, Q.REQ_QTY,                                        
(SELECT SUM(W.REQ_QTY) FROM #TEC_399_BATCH1 W WHERE W.IDX <= Q.IDX  AND W.REQ_QTY > 0) SUMQTY
FROM #TEC_399_BATCH1 Q) Z                                       
WHERE CASE WHEN (@BATCH_QTY1 - Z.SUMQTY) >= 0 THEN Z.REQ_QTY                                        
ELSE Z.REQ_QTY - (Z.SUMQTY - @BATCH_QTY1) END  > 0                             
*/


-- 임시 테이블: FIFO 재고 추적


DECLARE @BatchNo INT = 1;
DECLARE @Finished BIT = 0;
DECLARE @REQ_NO VARCHAR(50);
DECLARE @LOT_NO VARCHAR(50);
DECLARE @QTY_LEFT NUMERIC(18,3);
DECLARE @QtyToUse NUMERIC(18,3);


IF OBJECT_ID('tempdb..#FIFO_BATCH1') IS NOT NULL DROP TABLE #FIFO_BATCH1;
SELECT 
    REQ_NO,
    LOT_NO,
    REQ_QTY,
    REQ_QTY AS QTY_LEFT
INTO #FIFO_BATCH1
FROM #TEC_399_BATCH1
ORDER BY REQ_NO;

-- 사용 내역 기록 테이블
IF OBJECT_ID('tempdb..#BATCH1_USE_HIST') IS NOT NULL DROP TABLE #BATCH1_USE_HIST;
CREATE TABLE #BATCH1_USE_HIST (
    BATCH_NO INT,
    REQ_NO VARCHAR(50),
    LOT_NO VARCHAR(50),
    QTY_USED NUMERIC(18,3),
    QTY_LEFT NUMERIC(18,3)
);

WHILE @Finished = 0
BEGIN
    SET @QtyToUse = @BATCH_QTY1;

    WHILE @QtyToUse > 0 AND EXISTS (SELECT 1 FROM #FIFO_BATCH1 WHERE QTY_LEFT > 0)
    BEGIN
  

        SELECT TOP 1
            @REQ_NO = REQ_NO,
            @LOT_NO = LOT_NO,
            @QTY_LEFT = QTY_LEFT
        FROM #FIFO_BATCH1
        WHERE QTY_LEFT > 0
        ORDER BY REQ_NO;

        IF @QTY_LEFT <= @QtyToUse
        BEGIN
            INSERT INTO #BATCH1_USE_HIST(BATCH_NO, REQ_NO, LOT_NO, QTY_USED, QTY_LEFT)
            VALUES (@BatchNo, @REQ_NO, @LOT_NO, @QTY_LEFT, 0);

            SET @QtyToUse = @QtyToUse - @QTY_LEFT;

            UPDATE #FIFO_BATCH1 SET QTY_LEFT = 0 WHERE REQ_NO = @REQ_NO;
        END
        ELSE
        BEGIN
            INSERT INTO #BATCH1_USE_HIST(BATCH_NO, REQ_NO, LOT_NO, QTY_USED, QTY_LEFT)
            VALUES (@BatchNo, @REQ_NO, @LOT_NO, @QtyToUse, @QTY_LEFT - @QtyToUse);

            UPDATE #FIFO_BATCH1 SET QTY_LEFT = @QTY_LEFT - @QtyToUse WHERE REQ_NO = @REQ_NO;

            SET @QtyToUse = 0;
        END
    END

    SET @BatchNo = @BatchNo + 1;

    IF NOT EXISTS (SELECT 1 FROM #FIFO_BATCH1 WHERE QTY_LEFT > 0)
        SET @Finished = 1;
END
/*
-- 결과 확인
SELECT *
FROM #BATCH1_USE_HIST
ORDER BY BATCH_NO, REQ_NO;
*/

IF OBJECT_ID('tempdb..#FIFO_BATCH2') IS NOT NULL DROP TABLE #FIFO_BATCH2;
SELECT 
    REQ_NO,
    LOT_NO,
    REQ_QTY,
    REQ_QTY AS QTY_LEFT
INTO #FIFO_BATCH2
FROM #TEC_399_BATCH2
ORDER BY REQ_NO;

-- 사용 내역 기록 테이블
IF OBJECT_ID('tempdb..#BATCH2_USE_HIST') IS NOT NULL DROP TABLE #BATCH2_USE_HIST;
CREATE TABLE #BATCH2_USE_HIST (
    BATCH_NO INT,
    REQ_NO VARCHAR(50),
    LOT_NO VARCHAR(50),
    QTY_USED NUMERIC(18,3),
    QTY_LEFT NUMERIC(18,3)
);


SET @Finished = 0;
SET @BatchNo = 1;

WHILE @Finished = 0
BEGIN
    SET @QtyToUse = @BATCH_QTY2;  -- 배치 시작 시 초기화

    WHILE @QtyToUse > 0 AND EXISTS (SELECT 1 FROM #FIFO_BATCH2 WHERE QTY_LEFT > 0)
    BEGIN
        SELECT TOP 1
            @REQ_NO = REQ_NO,
            @LOT_NO = LOT_NO,
            @QTY_LEFT = QTY_LEFT
        FROM #FIFO_BATCH2
        WHERE QTY_LEFT > 0
        ORDER BY REQ_NO;

        IF @QTY_LEFT <= @QtyToUse
        BEGIN
            INSERT INTO #BATCH2_USE_HIST(BATCH_NO, REQ_NO, LOT_NO, QTY_USED, QTY_LEFT)
            VALUES (@BatchNo, @REQ_NO, @LOT_NO, @QTY_LEFT, 0);

            SET @QtyToUse = @QtyToUse - @QTY_LEFT;

            UPDATE #FIFO_BATCH2 SET QTY_LEFT = 0 WHERE REQ_NO = @REQ_NO;
        END
        ELSE
        BEGIN
            INSERT INTO #BATCH2_USE_HIST(BATCH_NO, REQ_NO, LOT_NO, QTY_USED, QTY_LEFT)
            VALUES (@BatchNo, @REQ_NO, @LOT_NO, @QtyToUse, @QTY_LEFT - @QtyToUse);

            UPDATE #FIFO_BATCH2 SET QTY_LEFT = @QTY_LEFT - @QtyToUse WHERE REQ_NO = @REQ_NO;

            SET @QtyToUse = 0;
        END
    END

    SET @BatchNo = @BatchNo + 1;

    IF NOT EXISTS (SELECT 1 FROM #FIFO_BATCH2 WHERE QTY_LEFT > 0)
        SET @Finished = 1;
END

-- 결과 확인
/*
SELECT *
FROM #BATCH2_USE_HIST
ORDER BY BATCH_NO, REQ_NO;
*/
-- 여기까지 왔다. 이 두테이블을 합쳐야 한다.
;
WITH B1 AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY BATCH_NO ORDER BY REQ_NO) AS RN
    FROM #BATCH1_USE_HIST
),
B2 AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY BATCH_NO ORDER BY REQ_NO) AS RN
    FROM #BATCH2_USE_HIST
)
SELECT 
    COALESCE(B1.BATCH_NO, B2.BATCH_NO) AS BATCH_NO,
    B1.REQ_NO AS BATCH1_REQ_NO,
    B1.LOT_NO AS BATCH1_LOT_NO,
    B1.QTY_USED AS BATCH1_USE_QTY,
    B2.REQ_NO AS BATCH2_REQ_NO,
    B2.LOT_NO AS BATCH2_LOT_NO,
    B2.QTY_USED AS BATCH2_USE_QTY
FROM B1
FULL OUTER JOIN B2
    ON B1.BATCH_NO = B2.BATCH_NO
   AND B1.RN = B2.RN
ORDER BY COALESCE(B1.BATCH_NO, B2.BATCH_NO), COALESCE(B1.RN, B2.RN);