ALTER PROC USP_POP_004_PROC_SPEC_DEL( 
     @DIV_CD        NVARCHAR(10)     = '01' 
    ,@PLANT_CD      NVARCHAR(10)     = '1140' 
    ,@ORDER_NO      NVARCHAR(50)     = 'PD231212003' 
    ,@REVISION      INT              = 2 
    ,@PROC_NO       NVARCHAR(50)     = 'OPL2312180005' 
    ,@ORDER_TYPE    NVARCHAR(10)     = 'PP01' 
    ,@ORDER_FORM    NVARCHAR(10)     = '10' 
    ,@ROUT_NO       NVARCHAR(10)     = 'C01' 
    ,@ROUT_VER      INT              = '1' 
    ,@WC_CD         NVARCHAR(10)     = '14GC' 
    ,@LINE_CD       NVARCHAR(10)     = '14G05C' 
    ,@S_CHK         NVARCHAR(1)      = 'N' 
    ,@PROC_CD       NVARCHAR(10)     = 'S' --RK, S, EU, ED, P 
    ,@RESULT_SEQ     INT  
    ,@CYCLE_SEQ     INT  
    ,@USER_ID       NVARCHAR(15)     = '' 
    ,@MSG_CD        NVARCHAR(4)      OUTPUT  
    ,@MSG_DETAIL    NVARCHAR(MAX)    OUTPUT  
 
) 
AS  
 
BEGIN TRY 
 
DELETE A  
        FROM PD_RESULT_PROC_SPEC_VALUE A WITH (NOLOCK)  
    WHERE A.DIV_CD = @DIV_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.ORDER_TYPE = @ORDER_TYPE AND A.ORDER_FORM = @ORDER_FORM  
      AND A.ROUT_NO = @ROUT_NO AND A.ROUT_VER = @ROUT_VER AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD  
      AND A.S_CHK = @S_CHK AND A.RESULT_SEQ = @RESULT_SEQ AND A.CYCLE_SEQ = @CYCLE_SEQ  
       
 
IF @PLANT_CD = '1150' AND @PROC_CD = 'PA'
BEGIN

    -- 현재 채번을 확인할것
    -- 이전 채번에 대한 내역을 삭제 해야 된다. 

    SET @CYCLE_SEQ = @CYCLE_SEQ - 1 

    DECLARE @BARCODE NVARCHAR(50) 
           ,@LOT_NO  NVARCHAR(50) 
           ,@ITEM_CD NVARCHAR(50) 
           ,@DC_ZMESIFNO     NVARCHAR(50) 
           ,@DC_DEL_ZMESIFNO NVARCHAR(50) 
    SELECT @BARCODE = B.BARCODE, @ITEM_CD = B.ITEM_CD, @LOT_NO = B.LOT_NO, @DC_ZMESIFNO = B.ZMESIFNO 
        FROM PD_RESULT A WITH (NOLOCK) 
        INNER JOIN PD_ITEM_IN B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDEr_NO = B.ORDER_NO 
        AND A.REVISION = B.REVISION AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO 
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.RESULT_SEQ = B.RESULT_SEQ AND B.PROC_CD = '*' 
        AND B.SEQ = @CYCLE_sEQ 
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION 
      AND A.ORDER_TYPE = @ORDER_TYPE AND A.ORDER_FORM = @ORDER_FORM AND A.ROUT_NO = @ROUT_NO AND A.ROUT_VER = @ROUT_VER 
      AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.RESULT_SEQ = @RESULT_SEQ 
    -- PALLET_MASTER 삭제
    
    DELETE A FROM 
    PALLET_MASTER A WITH (NOLOCK) 
    WHERE A.DIV_CD = @DIV_CD AND A.LOT_NO = @LOT_NO AND A.BARCODE = @BARCODE 

   
    -- SAP I/F 삭제
   
    EXEC USP_SAP_MESIFNO_CREATE @DIV_CD, @PLANT_CD, 'P060', @USER_ID, @DC_DEL_ZMESIFNO OUT   

    INSERT INTO SAP_Z02MESF_P060   
    (   
         CSYST			,ZMESIFNO			,WERKS			,AUFNR			,ZPROD   
        ,ZLOTNO			,CHARG				,VERID			,PRODMAT		,ZGRQTY   
        ,ZBAG			,ZLOT				,ZBAGN,FBAG		,MEINS			,ZAN   
        ,WORKER			,ZVAART				,ZSTORN			,ZMESIFNO_C		,MBLNR   
        ,MJAHR			,ZCRES				,ZCONF			,MESSAGE		,PMEMO  
        ,RETCD 			,RETMG			  
        ,MES_INS_DT		,MES_INS_ID			,MES_UPD_DT		,MES_UPD_ID   
    )   
    SELECT    
         CSYST		    ,@DC_DEL_ZMESIFNO	,WERKS			,AUFNR			,ZPROD   
        ,ZLOTNO			,CHARG				,VERID			,PRODMAT		,ZGRQTY   
        ,ZBAG			,ZLOT				,ZBAGN,FBAG		,MEINS			,ZAN   
        ,WORKER			,'R'				,'C'			,ZMESIFNO		,MBLNR   
        ,MJAHR			,ZCRES				,ZCONF			,MESSAGE		,PMEMO  
        ,NULL 			,NULL			  
        ,GETDATE()		,@USER_ID			,NULL			,NULL   
    FROM SAP_Z02MESF_P060 (NOLOCK)   
    WHERE WERKS = @PLANT_CD   
        AND ZMESIFNO = @DC_ZMESIFNO   
        AND CSYST = 'MES'   

     -- PD_ITEM_IN 삭제
    DELETE B
        FROM PD_RESULT A WITH (NOLOCK) 
        INNER JOIN PD_ITEM_IN B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDEr_NO = B.ORDER_NO 
        AND A.REVISION = B.REVISION AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO 
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.RESULT_SEQ = B.RESULT_SEQ AND B.PROC_CD = '*' 
        AND B.SEQ = @CYCLE_sEQ 
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION 
      AND A.ORDER_TYPE = @ORDER_TYPE AND A.ORDER_FORM = @ORDER_FORM AND A.ROUT_NO = @ROUT_NO AND A.ROUT_VER = @ROUT_VER 
      AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.RESULT_SEQ = @RESULT_SEQ 


END 

END TRY  
BEGIN CATCH  
    SET @MSG_CD = '9999' 
    SET @MSG_DETAIL = ERROR_MESSAGE()  
    RETURN 1  
END CATCH 