ALTER PROC USP_POP_003_ORDER_CAM3_PA_EQP
(
     @DIV_CD      NVARCHAR(10) 
    ,@PLANT_CD    NVARCHAR(10) 
    ,@WC_CD       NVARCHAR(10)
    ,@LINE_CD     NVARCHAR(10) 
    ,@PROC_CD     NVARCHAR(10) 
)
AS

SELECT A.TP AS CODE, A.EQP_NM AS NAME 
FROM BA_EQP A WITH (NOLOCK) WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.TP <> ''

