SELECT * from PD_MDM_RESULT_PROC_SPEC

UPDATE A SET A.END_DT = NULL
    FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
WHERE A.AUTO_NO = '252580001' AND A.SEQ = 5 --1~5

UPDATE A SET A.END_DT = NULL, VALUE = 100
    FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
WHERE A.AUTO_NO = '252630006' AND A.SEQ = 2 -- 1~4


UPDATE A SET A.AUTO_NO = '252580001' FROM PD_MDM_WORK_SEND A 
