ALTER PROC USP_MDM_CON_MAIN_QUERY   
AS   
/*
SELECT AA.DIV_CD, AA.PLANT_CD, AA.WC_CD, AA.WC_NM, AA.LINE_CD, AA.LINE_NM, AA.PROC_CD, AA.PROC_NM, AA.EQP_CD, AA.EQP_NM, AA.MN_S
FROM 
(  
    SELECT A.DIV_CD, A.PLANT_CD, A.WC_CD, B.WC_NM, C.LINE_CD, C.LINE_NM, A.PROC_CD, D.PROC_NM, CASE WHEN ISNULL(E.MN_S,'') <> '' THEN E.EQP_CD ELSE '' END 
    EQP_CD , 
    CASE WHEN ISNULL(E.MN_S,'') <> '' THEN E.EQP_NM ELSE '' END AS EQP_NM,
    A.PROC_SEQ, ISNULL(E.MN_S,'') AS MN_S
    --A.DIV_CD + ',' + A.PLANT_CD + ',' + A.WC_CD + ',' + B.WC_NM + ',' + C.LINE_CD + ',' + C.LINE_NM + ',' + A.PROC_CD + ',' + D.PROC_NM AS INFO   
        FROM BA_PROC_MAIN A WITH (NOLOCK)   
        INNER JOIN BA_WORK_CENTER B WITH (NOLOCK) ON A.DIV_CD = B.DIV_cD AND A.PLANT_CD = B.PLANT_CD AND A.WC_CD = B.WC_CD   
        INNER JOIN BA_LINE C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD   
        INNER JOIN BA_PROC D WITH (NOLOCK) ON A.PROC_CD = D.PROC_CD  
        INNER JOIN BA_EQP E WITH (NOLOCK) ON A.DIV_CD = E.DIV_cD AND A.PLANT_CD = E.PLANT_CD AND A.WC_CD = E.WC_CD 
        AND C.LINE_CD = E.LINE_CD AND A.PROC_CD = E.PROC_CD
        
    WHERE C.LINE_CD IN ('13G01A', '13G01B') AND A.PROC_CD IN ('RI','AI','MX', 'RK','RH','RB','EM','SI','PA')
--    GROUP BY A.DIV_CD, A.PLANT_CD, A.WC_CD, B.WC_NM, C.LINE_CD, C.LINE_NM, A.PROC_CD, D.PROC_NM, E.EQP_CD, E.EQP_NM, A.PROC_SEQ, E.MN_S
) AA 
GROUP BY AA.DIV_CD, AA.PLANT_CD, AA.WC_CD, AA.WC_NM, AA.LINE_CD, AA.LINE_NM, AA.PROC_CD, AA.PROC_NM, AA.EQP_CD, AA.EQP_NM, AA.MN_S, AA.PROC_SEQ
ORDER BY AA.WC_CD, AA.LINE_CD, AA.PROC_SEQ, AA.EQP_CD 
*/
--WHERE C.LINE_CD = '13G01A'
--RDER BY A.WC_CD, C.LINE_CD, A.PROC_SEQ 

WITH PROC_DATA AS (
    SELECT 
        A.DIV_CD, A.PLANT_CD, A.WC_CD, B.WC_NM,
        C.LINE_CD, C.LINE_NM,
        A.PROC_CD, D.PROC_NM,
        CASE WHEN ISNULL(E.MN_S,'') <> '' THEN E.EQP_CD ELSE '' END AS EQP_CD,
        CASE WHEN ISNULL(E.MN_S,'') <> '' THEN E.EQP_NM ELSE '' END AS EQP_NM,
        A.PROC_SEQ,
        ISNULL(E.MN_S,'') AS MN_S,
        MAX(CASE WHEN ISNULL(E.MN_S,'') <> '' THEN 1 ELSE 0 END) 
            OVER (PARTITION BY A.WC_CD, C.LINE_CD, A.PROC_CD) AS HAS_MN_S
    FROM BA_PROC_MAIN A
    INNER JOIN BA_WORK_CENTER B ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.WC_CD = B.WC_CD
    INNER JOIN BA_LINE C ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD
    INNER JOIN BA_PROC D ON A.PROC_CD = D.PROC_CD
    INNER JOIN BA_EQP E ON A.DIV_CD = E.DIV_CD AND A.PLANT_CD = E.PLANT_CD AND A.WC_CD = E.WC_CD
        AND C.LINE_CD = E.LINE_CD AND A.PROC_CD = E.PROC_CD
    WHERE C.LINE_CD IN ('13G01A', '13G01B')
      AND A.PROC_CD IN ('RI','AI','MX','RK','RH','RB','EM','SI','PA')
)
SELECT AA.*
FROM PROC_DATA AA 
WHERE NOT (AA.HAS_MN_S = 1 AND AA.MN_S = '')
GROUP BY AA.DIV_CD, AA.PLANT_CD, AA.WC_CD, AA.WC_NM, AA.LINE_CD, AA.LINE_NM, AA.PROC_CD, AA.PROC_NM, AA.EQP_CD, AA.EQP_NM, AA.MN_S, AA.PROC_SEQ, AA.HAS_MN_S

ORDER BY AA.WC_CD, AA.LINE_CD, AA.PROC_SEQ, AA.EQP_CD;
