ALTER PROC USP_MDM_CON_MAIN_QUERY   
AS   
  
SELECT A.DIV_CD, A.PLANT_CD, A.WC_CD, B.WC_NM, C.LINE_CD, C.LINE_NM, A.PROC_CD, D.PROC_NM  
--A.DIV_CD + ',' + A.PLANT_CD + ',' + A.WC_CD + ',' + B.WC_NM + ',' + C.LINE_CD + ',' + C.LINE_NM + ',' + A.PROC_CD + ',' + D.PROC_NM AS INFO   
    FROM BA_PROC_MAIN A WITH (NOLOCK)   
    INNER JOIN BA_WORK_CENTER B WITH (NOLOCK) ON A.DIV_CD = B.DIV_cD AND A.PLANT_CD = B.PLANT_CD AND A.WC_CD = B.WC_CD   
    INNER JOIN BA_LINE C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD   
    INNER JOIN BA_PROC D WITH (NOLOCK) ON A.PROC_CD = D.PROC_CD  
WHERE C.LINE_CD IN ('13G01A', '13G01B') AND A.PROC_CD IN ('RI','AI','MX', 'RK','RH','RB','EM','SI','PA')
--WHERE C.LINE_CD = '13G01A'
ORDER BY A.WC_CD, C.LINE_CD, A.PROC_SEQ 


