
/*
SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER A
WHERE A.InboundId_ApiAutoCreate > 3280 
  AND A.[CASE] LIKE '%리본%'

  SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER A
WHERE A.InboundId_ApiAutoCreate > 3280 
  AND A.[CASE] LIKE '%탈철%'

  SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER A
WHERE A.InboundId_ApiAutoCreate > 3280 
  AND A.[CASE] LIKE '%채분리%'

  SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER A
WHERE A.InboundId_ApiAutoCreate > 3280 
  AND A.[CASE] LIKE '%포장%'

*/

BEGIN TRAN

declare @p_InboundId int = 4203

DECLARE @I_VALUE INT 
,@MSG_CD NVARCHAR(4) 
,@MSG_DETAIL NVARCHAR(MAX)
-- 
EXEC @I_VALUE = USP_MDM_PROD_INFO_QUERY
@INBOUNDID = @p_InboundId --2285--2547--= '2570' 
,@MSG_CD = @MSG_CD OUTPUT 
,@MSG_DETAIL = @MSG_DETAIL OUTPUT

SELECT @I_VALUE, @MSG_CD, @MSG_DETAIL


SELECT 'MDM_RESULT_PROC_SPEC', A.*
FROM PD_MDM_RESULT_PROC_SPEC A
WHERE A.END_DT IS NULL
--AND PROC_CD <> 'AI'
SELECT *
FROM PD_MDM_RESULT_MASTER
WHERE EDATE IS NULL

ROLLBACK  
--commit 

