/*
105963
105965
106067
*/

BEGIN TRAN

declare @p_InboundId int = 106780

    

DECLARE @I_VALUE INT 
,@MSG_CD NVARCHAR(4) 
,@MSG_DETAIL NVARCHAR(MAX)
-- 
EXEC @I_VALUE = USP_MDM_PROD_INFO_QUERY
@INBOUNDID = @p_InboundId --2285--2547--= '2570' 
,@MSG_CD = @MSG_CD OUTPUT 
,@MSG_DETAIL = @MSG_DETAIL OUTPUT

SELECT @I_VALUE, @MSG_CD, @MSG_DETAIL


SELECT A.* FROM PD_MDM_RESULT_PROC_SPEC A
WHERE A.END_DT IS NULL

SELECT A.* FROM PD_MDM_RESULT_MASTER A 
WHERE A.EDATE IS NULL 


COMMIT 
