/*
----------------------------------------------------
MDM 실적 처리 Gathering 프로그램 기본 조회
----------------------------------------------------
작업일자 : 25.09.20 
작업자 : ljw
*/

ALTER PROC USP_PD_GAT_INFO_QUERY(
 @WC_CD          NVARCHAR(10) = '13GA'
,@LINE_CD        NVARCHAR(10) = '13G01A'
,@PROC_CD        NVARCHAR(10) = 'RI'
,@EQP_CD         NVARCHAR(50) = ''
,@USER_ID        NVARCHAR(15) = 'SCADA'
)
AS 

-- 참고로 원료 시작 말고는 
-- 실적 시작이 되어야지 TAG 매칭 처리가 되는 경우도 있으니 디버깅시에 한번 더 타봐야지 확인 가능한 부분이 있음.

SELECT 
TOP 1 
AA.PD_AUTO_NO, AA.AUTO_NO, AA.DIV_CD, AA.PLANT_CD, AA.ORDER_NO, AA.REVISION, AA.PROC_NO, AA.ORDER_TYPE, AA.ORDER_FORM, AA.ROUT_NO, AA.ROUT_VER, 
AA.WC_CD, AA.LINE_CD, AA.PROC_CD, AA.S_CHK, AA.RESULT_SEQ, AA.EQP_CD, AA.SPEC_CD, AA.VALUE, AA.VALUE_STR, AA.TAG_ID, AA.SEQ, 
AA.VALUE_STEP, AA.COL_CHK, ISNULL(AA.ROTATION,0) AS ROTATION, AA.START_DT, AA.GROUP_CHK, AA.OUT_CHK

FROM (
  -- 값이 있는것 위주 -> TAG 매칭 처리
  SELECT DISTINCT 
      A.PD_AUTO_NO, A.AUTO_NO,  D.DIV_CD, D.PLANT_CD, D.ORDER_NO, D.REVISION, D.PROC_NO, D.ORDER_TYPE, D.ORDER_FORM, D.ROUT_NO, D.ROUT_VER, 
      D.WC_CD, D.LINE_CD, D.PROC_CD, D.S_CHK, D.RESULT_SEQ, E.EQP_CD,
      CASE WHEN CHARINDEX('-',F.TEMP_CD4) = 0 THEN E.PROC_SPEC_CD ELSE 
      CASE WHEN CHARINDEX(E.PROC_SPEC_CD,F.TEMP_CD4) = 0 THEN E.PROC_SPEC_CD ELSE 
      CASE WHEN A.VALUE_STEP = 'DE' THEN 
          REPLACE(REPLACE(REPLACE(SUBSTRING(F.TEMP_CD4,0,CHARINDEX('-',F.TEMP_CD4)),' ' ,''),'[',''),']','')
          WHEN A.VALUE_STEP = 'DS' THEN 
          REPLACE(REPLACE(REPLACE(SUBSTRING(F.TEMP_CD4,CHARINDEX('-',F.TEMP_CD4) + 1, LEN(F.TEMP_CD4)),' ',''),'[',''),']','')
      END 
      END 
  END AS SPEC_CD 
  , A.VALUE
  , A.VALUE_STR
  , A.TAG_ID
  , A.SEQ, A.VALUE_STEP, A.COL_CHK, A.ROTATION, A.START_DT, A.GROUP_CHK, A.OUT_CHK
  FROM PD_MDM_RESULT_PROC_SPEC A
  INNER JOIN BA_EQP B WITH (NOLOCK) ON A.EQP_CD = B.EQP_CD AND A.PROC_CD = B.PROC_CD 
  INNER JOIN POP_EQP_ENO C WITH (NOLOCK) ON A.PROC_CD = C.PROC_CD AND B.EQP_CD = C.EQP_CD AND A.TAG_ID =  C.MDM_TAG
  INNER JOIN PD_RESULT D WITH (NOLOCK) ON A.ORDER_NO = D.ORDER_NO AND A.WC_CD = D.WC_CD AND A.LINE_CD = D.LINE_CD AND 
  A.PROC_CD = D.PROC_CD AND D.EDATE IS NULL AND D.S_CHK = 'N'
  AND D.EQP_CD = CASE WHEN B.MN_S IN ('Y','E') THEN A.EQP_CD ELSE D.EQP_CD END 
  LEFT JOIN PD_RESULT_PROC_SPEC_VALUE E WITH (NOLOCK) ON D.DIV_CD = E.DIV_CD AND D.PLANT_CD = E.PLANT_CD AND 
  D.ORDER_NO = E.ORDER_NO AND D.REVISION = E.REVISION AND D.ORDER_TYPE = E.ORDER_TYPE AND D.ORDER_FORM = E.ORDER_FORM AND 
  D.ROUT_NO = E.ROUT_NO AND D.ROUT_VER = E.ROUT_VER AND D.WC_CD = E.WC_CD AND D.LINE_CD = E.LINE_CD AND 
  D.PROC_CD = E.PROC_CD AND D.RESULT_SEQ = E.RESULT_SEQ AND E.CYCLE_SEQ = ISNULL(A.ROTATION,1) AND A.EQP_CD = E.EQP_CD AND C.PROC_SPEC_CD = E.PROC_SPEC_CD 
  LEFT JOIN BA_SUB_CD F WITH (NOLOCK) ON E.PROC_SPEC_CD = F.SUB_CD AND F.MAIN_CD = 'P2001'
  WHERE A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND 
        A.END_DT IS NULL AND E.EQP_CD IS NOT NULL
        AND A.EQP_CD LIKE @EQP_CD + '%'
  UNION ALL 
  -- 시작이나 종료
  SELECT A.PD_AUTO_NO, A.AUTO_NO, B.DIV_CD, B.PLANT_CD, A.ORDER_NO, B.REVISION, B.PROC_NO, B.ORDER_TYPE, B.ORDER_FORM, B.ROUT_NO, B.ROUT_VER, 
  A.WC_CD, A.LINE_CD, A.PROC_CD, 'N' AS S_CHK, 

  ISNULL((SELECT A1.RESULT_SEQ FROM PD_RESULT A1 WITH (NOLOCK) WHERE A1.DIV_CD = B.DIV_CD AND A1.PLANT_CD = B.PLANT_CD
  AND A1.ORDER_NO = A.ORDER_NO AND A1.WC_CD = A.WC_CD AND A1.LINE_CD = A.LINE_CD AND A1.PROC_CD = A.PROC_CD AND A1.EQP_CD = A.EQP_CD AND A1.EDATE IS NULL),(SELECT TOP 1 A1.RESULT_SEQ FROM PD_MDM_RESULT_MASTER A1 WITH (NOLOCK) WHERE A1.PD_AUTO_NO = A.PD_AUTO_NO 
  AND A1.AUTO_NO = A.AUTO_NO AND A1.ORDER_NO = A.ORDER_NO AND A1.WC_CD = A.WC_CD AND A1.LINE_CD = A.LINE_CD AND A1.PROC_CD = A.PROC_CD AND A1.EDATE IS NULL)
  )
  AS RESULT_SEQ, A.EQP_CD, '', A.VALUE, A.VALUE_STR, A.TAG_ID, A.SEQ, A.VALUE_STEP, A.COL_CHK, A.ROTATION, A.START_DT,
  A.GROUP_CHK, A.OUT_CHK 

      FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
      INNER JOIN PD_ORDER B WITH (NOLOCK) ON A.ORDER_NO = B.ORDER_NO AND B.CFM_FLG = 'Y' AND B.CLOSE_FLG = 'N'
      LEFT JOIN POP_EQP_ENO C WITH (NOLOCK) ON A.PROC_CD = C.PROC_CD AND A.EQP_CD = C.EQP_CD AND A.TAG_ID =  C.MDM_TAG

  WHERE A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.END_DT IS NULL 
    AND ISNULL(C.MDM_TAG,'') = ''
    AND A.EQP_CD LIKE @EQP_CD + '%'
) AA
order by aA.PD_auto_no, AA.AUTO_NO,  AA.SEQ 


SELECT A.EQP_CD
  FROM PD_MDM_RESULT_PROC_SPEC A
  INNER JOIN BA_EQP B WITH (NOLOCK) ON A.EQP_CD = B.EQP_CD AND A.PROC_CD = B.PROC_CD 
  INNER JOIN POP_EQP_ENO C WITH (NOLOCK) ON A.PROC_CD = C.PROC_CD AND B.EQP_CD = C.EQP_CD AND A.TAG_ID =  C.MDM_TAG
  INNER JOIN PD_RESULT D WITH (NOLOCK) ON A.ORDER_NO = D.ORDER_NO AND A.WC_CD = D.WC_CD AND A.LINE_CD = D.LINE_CD AND 
  A.PROC_CD = D.PROC_CD AND D.EDATE IS NULL AND D.S_CHK = 'N'
  AND D.EQP_CD = CASE WHEN B.MN_S IN ('Y','E') THEN A.EQP_CD ELSE D.EQP_CD END 
  LEFT JOIN PD_RESULT_PROC_SPEC_VALUE E WITH (NOLOCK) ON D.DIV_CD = E.DIV_CD AND D.PLANT_CD = E.PLANT_CD AND 
  D.ORDER_NO = E.ORDER_NO AND D.REVISION = E.REVISION AND D.ORDER_TYPE = E.ORDER_TYPE AND D.ORDER_FORM = E.ORDER_FORM AND 
  D.ROUT_NO = E.ROUT_NO AND D.ROUT_VER = E.ROUT_VER AND D.WC_CD = E.WC_CD AND D.LINE_CD = E.LINE_CD AND 
  D.PROC_CD = E.PROC_CD AND D.RESULT_SEQ = E.RESULT_SEQ AND E.CYCLE_SEQ = ISNULL(A.ROTATION,1) AND A.EQP_CD = E.EQP_CD AND C.PROC_SPEC_CD = E.PROC_SPEC_CD 
  LEFT JOIN BA_SUB_CD F WITH (NOLOCK) ON E.PROC_SPEC_CD = F.SUB_CD AND F.MAIN_CD = 'P2001'
  WHERE A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND 
        A.END_DT IS NULL-- AND E.EQP_CD IS NOT NULL
        AND A.EQP_CD LIKE @EQP_CD + '%'