/*SELECT *FROM PD_ORDER_PROC A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250929012'
ORDER BY A.GROUP_SEQ

UPDATE A SET A.PROC_SEQ = A.PROC_SEQ + 1, A.GROUP_SEQ = A.GROUP_SEQ + 1
    FROM PD_ORDER_PROC A
WHERE A.ORDER_NO = 'PD250929012' 
  AND A.PROC_CD IN ('EM','PA')

UPDATE A SET A.PROC_CD = 'RB' FROM PD_ORDER_PROC_spec A
WHERE A.ORDER_NO = 'PD250929012' 
  AND A.PROC_CD = 'SE'


update a set a.proc_cd = 'RB' from ba_eqp a with (nolock) 
where a.plant_cd = '1130' and a.line_cd = '13g01b' and a.proc_cd = 'se'


UPDATE  A SET A.PROC_CD = 'SI'
FROM PD_ORDER_PROC_SPEC A
WHERE A.ORDER_NO = 'PD251029092' AND A.PROC_CD = 'SE' AND A.EQP_CD 
--IN ('LFG01A-01B-RM-0502','LFG01A-01B-RM-0501')
IN ('LFG01A-01B-VS-0501' ,'LFG01A-01B-VS-0502')

UPDATE A SET A.PROC_CD = 'SI' from ba_eqp a with (nolock) 
where a.plant_cd = '1130' and a.line_cd = '13g01b' and a.proc_cd = 'RB'
AND A.EQP_CD IN (
'LFG01A-01B-VS-0501' ,'LFG01A-01B-VS-0502'


UPDATE A SET A.PROC_CD = 'RB' FROM POP_EQP_ENO A WITH (NOLOCK) 
WHERE A.PROC_CD = 'SE' AND A.PLANT_CD = '1130' AND A.EQp_CD 
IN ('LFG01A-01B-RM-0502','LFG01A-01B-RM-0501')
)

UPDATE A SET A.PROC_CD = 'SI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
WHERE A.PROC_CD = 'SE' AND A.PLANT_CD = '1130' AND A.EQp_CD 
IN ('LFG01A-01B-VS-0501' ,'LFG01A-01B-VS-0502')


PD250929012
PD251029092

UPDATE A SET A.PROC_CD = 'RB' FROM PD_ORDER_PROC A
WHERE ORDER_NO = 'PD251029092' AND PROC_CD = 'SE'
*/


--SP_HELP PD_ORDER_PROC_SPEC 

BEGIN TRAN 
INSERT INTO PD_ORDER_PROC_SPEC 
select 
A.DIV_CD
,A.PLANT_CD
,'PD250929011'
,2
,A.ORDER_TYPE
,A.ORDER_FORM
,A.ROUT_NO
,A.ROUT_VER
,A.WC_CD
,A.LINE_CD
,A.PROC_CD
,A.SEQ
,A.SPEC_VERSION
,A.BASE_ITEM_CD
,A.MODEL
,A.STEP
,A.GROUP_SPEC_CD
,A.PROC_SPEC_CD
,A.EQP_CD
,A.RECYCLE_NO
,A.BASIC_UNIT
,A.SPEC_VALUE_TYPE
,A.USEM_ITEM_GROUP
,A.PROC_SPEC_U
,A.PROC_SPEC_L
,A.PROC_SPEC_VALUE
,A.PROC_SPEC_SETTING
,A.PROC_EQP_U
,A.PROC_EQP_L
,A.PROC_SETTING_VALUE
,A.PROC_DIGIT
,A.PROC_WARNING_U
,A.PROC_WARNING_L
,A.WARNING_TYPE
,A.PLC_FLAG
,A.CHK_FLAG
,A.REQ_FLAG
,A.REV_FLAG
,A.BYPASS_FLAG
,A.SET_FLAG
,A.AUTO_PLC_FLAG
,A.STOCK_ADD
,A.INQ_TYPE
,A.REMARK
,A.USE_YN
,A.CFM_FLG
,A.INSERT_ID
,A.INSERT_DT
,A.UPDATE_ID
,A.UPDATE_DT
,A.FMEA_CP_SEQ
--INSERT INTO PD_ORDER_PROC_SPEC 
--SELECT A.*
FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
LEFT JOIN PD_ORDER_PROC_SPEC B WITH (NOLOCK) ON A.LINE_CD = B.LINE_CD 
AND A.PROC_CD = B.PROC_CD 
AND A.PROC_SPEC_CD = B.PROC_SPEC_CD AND A.EQP_CD = B.EQP_CD AND B.ORDER_NO = 'PD250929011'
WHERE A.ORDEr_NO = 'PD251029091'
AND B.PROC_SPEC_CD IS NULL AND ISNULL(A.USEM_ITEM_GROUP,'') <> '' 

INSERT INTO PD_ORDER_PROC_SPEC 

select 
A.DIV_CD
,A.PLANT_CD
,'PD250929012'
,2
,A.ORDER_TYPE
,A.ORDER_FORM
,A.ROUT_NO
,A.ROUT_VER
,A.WC_CD
,A.LINE_CD
,A.PROC_CD
,A.SEQ
,A.SPEC_VERSION
,A.BASE_ITEM_CD
,A.MODEL
,A.STEP
,A.GROUP_SPEC_CD
,A.PROC_SPEC_CD
,A.EQP_CD
,A.RECYCLE_NO
,A.BASIC_UNIT
,A.SPEC_VALUE_TYPE
,A.USEM_ITEM_GROUP
,A.PROC_SPEC_U
,A.PROC_SPEC_L
,A.PROC_SPEC_VALUE
,A.PROC_SPEC_SETTING
,A.PROC_EQP_U
,A.PROC_EQP_L
,A.PROC_SETTING_VALUE
,A.PROC_DIGIT
,A.PROC_WARNING_U
,A.PROC_WARNING_L
,A.WARNING_TYPE
,A.PLC_FLAG
,A.CHK_FLAG
,A.REQ_FLAG
,A.REV_FLAG
,A.BYPASS_FLAG
,A.SET_FLAG
,A.AUTO_PLC_FLAG
,A.STOCK_ADD
,A.INQ_TYPE
,A.REMARK
,A.USE_YN
,A.CFM_FLG
,A.INSERT_ID
,A.INSERT_DT
,A.UPDATE_ID
,A.UPDATE_DT
,A.FMEA_CP_SEQ
FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
LEFT JOIN PD_ORDER_PROC_SPEC B WITH (NOLOCK) ON A.LINE_CD = B.LINE_CD 
AND A.PROC_CD = B.PROC_CD 
AND A.PROC_SPEC_CD = B.PROC_SPEC_CD AND A.EQP_CD = B.EQP_CD AND B.ORDER_NO = 'PD250929012'
WHERE A.ORDEr_NO = 'PD251029092'
  AND B.PROC_SPEC_CD IS NULL --AND A.PROC_CD <> 'SE'
  AND ISNULL(A.USEM_ITEM_GROUP,'') <> '' 

ROLLBACK

