SELECT --LEFT(A.EQP_CD,6) + SUBSTRING(A.EQP_CD,11,LEN(A.EQP_CD))
A.*
FROM BA_ROUT_PROC_SPEC A WITH (NOLOCK) 
INNER JOIN BA_ROUT_PROC_SPEC B WITH (NOLOCK) ON A.ROUT_NO = B.ROUT_NO AND A.VERSION = B.VERSION 
AND A.PROC_SPEC_CD = B.PROC_SPEC_CD AND LEFT(A.EQP_CD,6) + SUBSTRING(A.EQP_CD,11,LEN(A.EQP_CD)) = LEFT(B.EQP_CD,6) + SUBSTRING(B.EQP_CD,11,LEN(B.EQP_CD))
AND A.PROC_CD = B.PROC_CD 
WHERE A.ROUT_NO = 'A01' AND A.LINE_CD = '13G01A'

SELECT A.*
FROM BA_ROUT_PROC_SPEC A WITH (NOLOCK) 
WHERE A.ROUT_NO = 'A01' AND A.LINE_CD = '13G02A'

SELECT C.*FROM BA_EQP A WITH (NOLOCK) 
INNER JOIN POP_EQP_ENO B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD 
AND A.PROC_CD = B.PROC_CD AND A.EQP_CD = B.EQP_CD AND ISNULL(B.MDM_TAG,'') <> '' 
LEFT JOIN BA_ROUT_PROC_SPEC C WITH (NOLOCK) ON B.DIV_CD = C.DIV_CD AND B.PLANT_CD = C.PLANT_CD 
AND A.LINE_CD = C.LINE_CD AND B.PROC_SPEC_CD = C.PROC_SPEC_CD AND B.EQP_CD = C.EQP_CD AND C.ROUT_NO = 'B01'
WHERE A.LINE_CD = '13G01B'
--  AND C.EQP_CD IS NULL 

SELECT A.* FROM BA_ROUT_PROC_SPEC A WITH (NOLOCK) 
INNER JOIN BA_EQP B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD 
AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD 
AND A.PROC_CD = B.PROC_CD AND A.EQP_CD = B.EQP_CD 
LEFT JOIN POP_EQP_ENO C WITH (NOLOCK) ON B.DIV_CD = C.DIV_CD AND B.PLANT_CD = C.PLANT_CD 
AND B.PROC_CD = C.PROC_CD AND B.EQP_CD = C.EQP_cD AND A.PROC_SPEC_CD = C.PROC_SPEC_CD AND ISNULL(C.MDM_TAG,'') <> ''
WHERE A.ROUT_NO = 'B01' AND A.LINE_CD = '13G02B'
--  AND A.USEM_ITEM_GROUP = '' 
