USE FLEXMES_ABB
GO 

DECLARE --@PLANT_CD      NVARCHAR(4) = '1140' -- PLANT 제외하고 TOTAL 로 보겠습니다.
       @MONTH         NVARCHAR(7) = '2025-10'
      ,@ITEM          NVARCHAR(10) = 'NE-K12S'       
-- 품목군
DECLARE @ITEM_GROUP TABLE (
     CNT              INT IDENTITY(1,1)
    ,BASE_ITEM_CD     NVARCHAR(50) -- 품종
)

--NE-K12S
--NXA-X12M

INSERT INTO @ITEM_GROUP 
(
     BASE_ITEM_CD
)

SELECT SUB_cD
FROM BA_SUB_CD A WITH (NOLOCK) 
WHERE A.MAIN_CD = 'BA206' AND A.SUB_NM LIKE @ITEM + '%'


-- 1. 투입량

SELECT A.PLANT_CD, A.WC_CD, A.LINE_CD, A.SIL_DT, E.BASE_ITEM_CD,  
(SELECT SUB_NM FROM BA_SUB_CD WHERE MAIN_CD = 'BA206' AND SUB_CD = E.BASE_ITEM_CD) AS BASE_ITEM_NM,
D.ITEM_CD, E.ITEM_NM, A.PROC_CD, F.PROC_NM, SUM(D.USEM_QTY) AS USEM_QTY 
FROM PD_RESULT A WITH (NOLOCK)
INNER JOIN PD_ORDER B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO 
AND A.REVISION = B.REVISION AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO 
AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD 
-- 품종의 지시를 모두 걸러낸뒤
INNER JOIN PD_ORDER_PROC C WITH (NOLOCK) ON B.DIV_CD = C.DIV_CD AND B.PLANT_CD = C.PLANT_CD AND B.PROC_NO = C.PROC_NO 
AND A.PROC_CD = C.PROC_CD AND C.IN_CHK = 'Y'
-- 해당 지시 그룹(PROC_NO) 에서 투입 공정을 모두 찾는다. 소분은 뺌. (포함 시켜야 하나?)
INNER JOIN PD_USEM D WITH (NOLOCK) ON A.DIV_CD = D.DIV_CD AND A.PLANT_CD = D.PLANT_CD AND A.ORDER_NO = D.ORDER_NO 
AND A.REVISION = D.REVISION AND A.ORDER_TYPE = D.ORDER_TYPE AND A.ORDER_FORM = D.ORDER_FORM AND A.ROUT_NO = D.ROUT_NO 
AND A.ROUT_VER = D.ROUT_VER AND A.WC_CD = D.WC_CD AND A.LINE_CD = D.LINE_CD AND A.PROC_CD = D.PROC_CD AND A.RESULT_SEQ = D.RESULT_SEQ 
-- 상세 투입 내역을 확인
INNER JOIN V_ITEM E WITH (NOLOCK) ON D.PLANT_CD = E.PLANT_CD AND D.ITEM_CD = E.ITEM_CD 
INNER JOIN BA_PROC F WITH (NOLOCK) ON A.PROC_CD = F.PROC_CD 

INNER JOIN V_ITEM Y WITH (NOLOCK) ON A.PLANT_CD = Y.PLANT_CD AND A.ITEM_CD = Y.ITEM_CD 
INNER JOIN @ITEM_GROUP Z ON Y.BASE_ITEM_CD = Z.BASE_ITEM_CD
WHERE 1=1 --A.PLANT_CD = @PLANT_CD 
--AND A.PROC_CD IN ('PA','CP') -- 포장
AND A.SIL_DT >=@MONTH + '-01' 
AND A.SIL_DT < DATEADD(MONTH,1,CAST(@MONTH + '-01' AS DATE))

GROUP BY A.PLANT_CD, A.WC_CD, A.LINE_CD, A.SIL_DT, D.ITEM_CD, E.ITEM_NM, A.PROC_CD, F.PROC_NM, E.BASE_ITEM_CD
--, G.SUB_NM
ORDER BY A.PLANT_CD, A.WC_CD, A.LINE_CD, D.ITEM_CD, A.SIL_DT

-- 2. 생산실적

SELECT A.PLANT_CD, A.WC_CD, A.LINE_CD, B.BASE_ITEM_CD, A.SIL_DT, D.SUB_NM, A.ITEM_CD, B.ITEM_NM, 
A.PROC_CD, C.PROC_NM, SUM(A.GOOD_QTY) AS GOOD_QTY 
FROM PD_RESULT A WITH (NOLOCK)
INNER JOIN V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.ITEM_CD = B.ITEM_CD 
INNER JOIN BA_PROC C WITH (NOLOCK) ON A.PROC_CD = C.PROC_CD 
INNER JOIN BA_SUB_CD D WITH (NOLOCK) ON B.BASE_ITEM_CD = D.SUB_CD AND D.MAIN_CD = 'BA206'
INNER JOIN @ITEM_GROUP E ON B.BASE_ITEM_CD = E.BASE_ITEM_CD
WHERE 1=1 --A.PLANT_CD = @PLANT_CD 
AND A.PROC_CD IN ('PA','CP') -- 포장
AND A.SIL_DT >=@MONTH + '-01' 
AND A.SIL_DT < DATEADD(MONTH,1,CAST(@MONTH + '-01' AS DATE))
GROUP BY A.PLANT_CD, B.BASE_ITEM_CD, D.SUB_NM, A.ITEM_CD, B.ITEM_NM, A.WC_CD, A.LINE_CD, A.PROC_CD, C.PROC_NM, A.SIL_DT
ORDER BY A.PLANT_CD, A.WC_CD, A.LINE_CD, B.BASE_ITEM_CD, A.SIL_DT

