-- 배정표 조회
-- PARAM
DECLARE 
        @DIV_CD      NVARCHAR(10) = '01'
       ,@PLANT_CD    NVARCHAR(10) = '1130'
       ,@WC_CD       NVARCHAR(10)
       ,@LINE_CD     NVARCHAR(10) 


DECLARE @REQ_DT NVARCHAR(7) = CONVERT(NVARCHAR(7), GETDATE(), 120)
       ,@ORDER_NO NVARCHAR(50) = ''

DECLARE @BATCH_TBL TABLE (
     ORDER_NO      NVARCHAR(50) 
    ,ITEM_CD       NVARCHAR(50) 
    ,ITEM_NM       NVARCHAR(100)
    ,REQ_NO        NVARCHAR(50)
    ,REQ_DT        NVARCHAR(7) 
    ,BATCH_NO      INT 
    ,PLAN_SEQ      INT 
    ,USE_QTY       NUMERIC(18,3) 
    ,USE_FLG       NVARCHAR(1) 
    ,CHG_RSN       NVARCHAR(10) 
    

)
INSERT INTO @BATCH_TBL 
SELECT A.ORDER_NO, A.ITEM_CD, B.ITEM_NM, A.REQ_NO, A.REQ_DT, A.BATCH_NO, A.PLAN_SEQ, A.USE_QTY, A.USE_FLG, A.CHG_RSN 
FROM MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
INNER JOIN V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.ITEM_CD = B.ITEM_CD 
WHERE A.REQ_DT = @REQ_DT AND ISNULL(A.CHG_RSN,'') = '' AND A.USE_FLG = 'Y' 
  AND A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
ORDER BY A.REQ_NO


-- 지시 정보들을 출력한다. 

SELECT 
       FROM PD_ORDER A WITH (NOLOCK)
WHERE A.PLANT_CD = @PLANT_CD 
