ALTER PROC USP_POP_004_CP_MATCH_ORDER 
(
     @DIV_CD    NVARCHAR(10) 
    ,@PLANT_CD  NVARCHAR(10) 
    ,@WC_CD     NVARCHAR(10) 
    ,@LINE_CD   NVARCHAR(10) 

)
as 

SELECT A.ORDER_NO AS CODE, 
A.ITEM_CD + ':' + B.ITEM_NM +
CASE WHEN ISNULL(C.SUB_NM,'') = '' THEN '' ELSE '/' + C.SUB_NM END AS NAME
    FROM PD_ORDER A WITH (NOLOCK) 
INNER JOIN V_ITEM B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.ITEM_CD = B.ITEM_CD 
INNER JOIN BA_SUB_CD C WITH (NOLOCK) ON B.ITEM_GROUP_CD2 = C.SUB_CD AND C.MAIN_CD = 'B0002'
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD 
    AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
    AND A.CLOSE_FLG = 'N'
