ALTER PROC USP_POP_004_CP_MATCH_QUERY
(
    @DIV_CD       NVARCHAR(10) 
    ,@PLANT_CD    NVARCHAR(10) 
    ,@WC_CD       NVARCHAR(15) 
    ,@LINE_CD     NVARCHAR(15) 
    ,@PROC_CD     NVARCHAR(15)
    ,@ORDER_NO    NVARCHAR(50)
)
AS 

SELECT A.RECYCLE_NO AS CYCLE_SEQ, A.SEQ, 

CASE WHEN EXISTS(SELECT TOP 1 *FROM PD_ORDER_CP_SPEC WITH (NOLOCK) 
WHERE DIV_CD = A.DIV_CD AND PLANT_CD = A.PLANT_CD AND ORDER_NO = A.ORDER_NO 
AND WC_CD =A.WC_CD AND LINE_CD = A.LINE_CD AND PROC_CD =A.PROC_CD AND MES_CP_CODE = A.PROC_SPEC_CD 
AND EQP_CD = A.EQP_CD 
ORDER BY ORDER_NO, REVISION DESC
) THEN 'Y' ELSE 'N' END 

AS MATCH_YN, D.SUB_NM AS SPEC_VALUE_TYPE, A.PROC_SPEC_CD AS SPEC_CD, B.SUB_NM AS SPEC_NM, A.EQP_CD, 
C.EQP_NM, A.PROC_SPEC_U, A.PROC_SPEC_L, A.PROC_SPEC_VALUE, A.USEM_ITEM_GROUP
    FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
    INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
    INNER JOIN BA_EQP C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.EQP_CD = C.EQP_CD 
    INNER JOIN BA_SUB_CD D WITH (NOLOCK) ON A.SPEC_VALUE_TYPE = D.SUB_CD AND D.MAIN_CD = 'P2002'
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
AND A.PROC_CD = @PROC_CD AND A.ORDER_NO = @ORDER_NO 
ORDER BY A.SEQ 

