BEGIN TRAN 
--113GB,13G02B,MX,LFG01A-02B-TK-0502


DECLARE @I_VALUE INT = 0
       
       ,@ORDER_NO NVARCHAR(50) 
       ,@REVISION INT 
       ,@RESULT_SEQ INT 
-- 13GB,13G02B,RH,LFG01A-02B-RCV-0401
EXEC @I_VALUE = USP_MDM_WORK_ORDER_CREATE
@DIV_CD = '01' 
,@PLANT_CD = '1130' 
,@WC_CD = '13GB'
,@LINE_CD = '13G02B' 
,@PROC_CD = 'MX'
,@EQP_CD = 'LFG01A-02B-TK-0502'
,@VALUE = 3000
,@ORDEr_NO = @ORDER_NO OUTPUT 
,@REVISION = @REVISION OUTPUT 
,@RESULT_SEQ = @RESULT_SEQ OUTPUT 


SELECT @I_VALUE, @ORDER_NO, @REVISION, @RESULT_SEQ 


ROLLBACK 




--ORDER BY PROC_SEQ 

