BEGIN TRAN 

DECLARE @NEW_ORDER TABLE 
(
  ORDER_NO NVARCHAR(50) 
)

INSERT INTO @NEW_ORDER 
SELECT A.MES_ORDER_NO FROM FLEXMES_ABB.DBO.SAP_Z02MESF_P010_DTL A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002023'


DELETE MT_ITEM_OUT_BATCH 
WHERE ORDER_NO = 'PD250929013'
INSERT INTO MT_ITEM_OUT_BATCH
SELECT *FROM FLEXMES_ABB.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250929013'


-- 배정 수정 
UPDATE A SET A.REQ_DT = '2025-12'
FROM MT_ITEM_OUT_BATCH A
WHERE A.ORDER_NO = 'PD250929013'


SELECT *FROM @NEW_ORDER 


SELECT *FROM PD_ORDER A WITH (NOLOCK) WHERE A.ORDER_NO = 'PD251013001'
/*
INSERT INTO SAP_Z02MESF_P010_HDR
SELECT A.* FROM FLEXMES_ABB.DBO.SAP_Z02MESF_P010_HDR A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002023'

INSERT INTO SAP_Z02MESF_P010_DTL
SELECT A.* FROM FLEXMES_ABB.DBO.SAP_Z02MESF_P010_DTL A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002023'

INSERT INTO SAP_Z02MESF_P010_USEM
SELECT A.* FROM FLEXMES_ABB.DBO.SAP_Z02MESF_P010_USEM A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002023'

*/
INSERT INTO PD_ORDER
SELECT *FROM FLEXMES_ABB.DBO.PD_ORDER A WITH (NOLOCK) 
WHERE A.ORDEr_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)

INSERT INTO PD_ORDER_USEM
SELECT 
 DIV_CD
,PLANT_CD
,ORDER_NO
,REVISION
,ORDER_TYPE
,ORDER_FORM
,ROUT_NO
,ROUT_VER
,WC_CD
,LINE_CD
,PROC_CD
,USEM_SEQ
,ITEM_CD
,NULL
,BASE_ITEM_CD
,USEM_QTY
,REMARK
,CFM_FLG
,INSERT_ID
,INSERT_DT
,UPDATE_ID
,UPDATE_DT
,AUFNR
,VORNR
,RSNUM
,RSPOS
,BWART
FROM FLEXMES_ABB.DBO.PD_ORDER_USEM A WITH (NOLOCK) 
WHERE A.ORDEr_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)

INSERT INTO PD_ORDER_PROC 
SELECT A.* FROM FLEXMES_ABB.DBO.PD_ORDER_PROC A WITH (NOLOCK) 
WHERE A.ORDEr_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)


INSERT INTO PD_ORDER_PROC_SPEC 
SELECT 
 DIV_CD
,PLANT_CD
,ORDER_NO
,REVISION
,ORDER_TYPE
,ORDER_FORM
,ROUT_NO
,ROUT_VER
,WC_CD
,LINE_CD
,PROC_CD
,SEQ
,SPEC_VERSION
,BASE_ITEM_CD
,NULL
,STEP
,GROUP_SPEC_CD
,PROC_SPEC_CD
,EQP_CD
,RECYCLE_NO
,BASIC_UNIT
,SPEC_VALUE_TYPE
,USEM_ITEM_GROUP
,PROC_SPEC_U
,PROC_SPEC_L
,PROC_SPEC_VALUE
,PROC_SPEC_SETTING
,PROC_EQP_U
,PROC_EQP_L
,PROC_SETTING_VALUE
,PROC_DIGIT
,PROC_WARNING_U
,PROC_WARNING_L
,WARNING_TYPE
,PLC_FLAG
,CHK_FLAG
,REQ_FLAG
,REV_FLAG
,BYPASS_FLAG
,SET_FLAG
,AUTO_PLC_FLAG
,STOCK_ADD
,INQ_TYPE
,REMARK
,USE_YN
,CFM_FLG
,INSERT_ID
,INSERT_DT
,UPDATE_ID
,UPDATE_DT
,NULL
FROM FLEXMES_ABB.DBO.PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
WHERE A.ORDEr_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)



/*
-- 배정 등록
INSERT INTO MT_ITEM_OUT_BATCH
SELECT *FROM FLEXMES_ABB.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)


-- 배정 수정 
UPDATE A SET A.REQ_DT = '2025-12'
FROM MT_ITEM_OUT_BATCH A
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)


--재고 확인
--SELECT TOP 10 *FROM ST_STOCK_NOW 

INSERT INTO ST_STOCK_NOW
SELECT DISTINCT B.DIV_CD, B.PLANT_CD, B.ITEM_CD, B.LOT_NO, B.WC_CD, B.PROC_CD, B.SL_CD, B.LOCATION_NO, B.RACK_CD, B.BARCODE, 
B.QTY, 'S', B.INSERT_ID, B.INSERT_DT FROM FLEXMES_ABB.DBO.MT_ITEM_OUT_BATCH A WITH (NOLOCK) 
INNER JOIN FLEXMES_ABB.DBO.ST_STOCK_NOW B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND  A.ITEM_CD = B.ITEM_CD AND A.LOT_NO = B.LOT_NO AND B.PROC_CD = '*' 
AND B.SL_CD = '3000' AND B.BARCODE <> '*' AND B.QTY > 0
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)
-- 설비코드 확인 

UPDATE A SET A.EQP_CD = B.EQP_CD FROM  PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
INNER JOIN  BA_EQP B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.EQP_CD = B.EQP_BACK AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)
*/



/*
SELECT A.EQP_CD FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)

SELECT *FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
LEFT JOIN BA_EQP B WITH (NOLOCK) ON A.PLANT_CD = B.PLANT_CD AND A.EQP_CD = B.EQP_CD AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)
  AND B.EQP_CD IS NULL


UPDATE A SET A.EQP_CD = B.EQP_CD FROM BA_ROUT_PROC_SPEC A WITH (NOLOCK) 
INNER JOIN BA_EQP B WITH (NOLOCK) ON A.EQP_CD = B.EQP_BACK 
WHERE A.LINE_CD IN ('13G02A','13G02B') AND A.CAPA_TYPE = 'PP03'

SELECT A.*
FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
INNER JOIN BA_ROUT_PROC_SPEC B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.VERSION
AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.EQP_CD = B.EQP_CD
AND A.PROC_SPEC_CD = B.PROC_SPEC_CD
WHERE A.ORDER_NO IN (SELECT ORDER_NO FROM @NEW_ORDER)
ORDER BY A.PROC_CD 

*/
/*
SELECT REPLACE(MDM_TAG,'LFG01A-01','LFG01A-02'), *FROM POP_EQP_ENO A WITH (NOLOCK) 
WHERE ISNULL(A.MDM_TAG,'') <> '' 
ORDER BY EQP_CD, SPEC_SEQ


UPDATE A SET A.LOEKZ = '' FROM SAP_Z02MESF_P010_HDR A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002038'

SELECT A.*FROM SAP_Z02MESF_P010_DTL A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002038'

UPDATE A SET A.XLOEK ='' FROM SAP_Z02MESF_P010_USEM A WITH (NOLOCK) 
WHERE A.AUFNR = '000010002038'
*/


ROLLBACK 



