BEGIN TRAN 
DECLARE @ORDER_NO NVARCHAR(50) = ''
,@REVISION INT = 0 
,@RESULT_SEQ INT = 0

EXEC USP_MDM_WORK_ORDER_CREATE 
        @DIV_CD = '01', @PLANT_CD = '1130', @WC_CD = '13GB', @LINE_CD = '13G01B', @PROC_CD = 'RH',
        @EQP_CD = 'LFG01A-01B-PS-0301', @VALUE = 3000, @ORDER_NO = @ORDER_NO OUTPUT, @REVISION = @REVISION OUTPUT, 
        @RESULT_SEQ = @RESULT_SEQ OUTPUT 

SELECT @ORDER_NO, @REVISION, @RESULT_SEQ 


ROLLBACK 

