/*  
기안번호 : PM250912007	  
기안구분 : 일반  
제목 : 실적 관련 모든 테이블 LOG 적재
일자 : 2025-09-17
작업자 : 임종원 이사  
*/    

 
/*==============================================================================                             
+ PROCEDURE 명 : USP_PRD_010W_DELETE2   
+ 관 련  업 무 : 생산실적 수정 - 삭제(실적별)   
+ 작   업   자 : 정유영   
+ 작 업  일 자 : 2024.02.19   
+ 비        고 :    
==============================================================================*/   
ALTER PROCEDURE [dbo].[USP_PRD_010W_DELETE2]   
(   
	 @CUD_CHAR		NVARCHAR(1)		= ''  
	,@DIV_CD		NVARCHAR(10)	= ''  
	,@PLANT_CD		NVARCHAR(10)	= ''  
	,@PROC_NO		NVARCHAR(50)	= ''  
	,@ORDER_NO		NVARCHAR(50)	= ''  
	,@REVISION		INT				= 0  
	,@ORDER_TYPE	NVARCHAR(10)	= ''  
	,@ORDER_FORM	NVARCHAR(10)	= ''  
	,@ROUT_NO		NVARCHAR(10)	= ''  
	,@ROUT_VER		INT				= 0  
	,@WC_CD			NVARCHAR(10)	= ''  
	,@LINE_CD		NVARCHAR(10)	= ''  
	,@PROC_CD		NVARCHAR(10)	= ''  
	,@S_CHK			NVARCHAR(1)		= ''  
	,@RESULT_SEQ	INT				= 0  
	,@USER_ID		NVARCHAR(15)	= ''  
   
	,@MSG_CD		NVARCHAR(4)		= ''    OUTPUT  
	,@MSG_DETAIL	NVARCHAR(MAX)	= ''    OUTPUT  
) AS   
SET NOCOUNT ON   
BEGIN  
  
	DECLARE @TB_DELETE_RESULT	TABLE  
	(  
		 DIV_CD			NVARCHAR(10)  
		,PLANT_CD		NVARCHAR(10)  
		,PROC_NO		NVARCHAR(50)  
		,ORDER_NO		NVARCHAR(50)  
		,REVISION		INT  
		,ORDER_TYPE		NVARCHAR(10)  
		,ORDER_FORM		NVARCHAR(10)  
		,ROUT_NO		NVARCHAR(10)  
		,ROUT_VER		INT  
		,WC_CD			NVARCHAR(10)  
		,LINE_CD		NVARCHAR(10)  
		,PROC_CD		NVARCHAR(10)  
		,S_CHK			NVARCHAR(1)  
		,RESULT_SEQ		INT  
		,LOT_SEQ		INT  
		,SIL_DT			DATE			  
		,OUT_CHK		NVARCHAR(1)  
		,GROUP_SEQ		INT  
	)  
	  
	DECLARE @TB_SAP_IF	TABLE   
	(   
		 SEQ		INT  
		,ZMESIFNO	NVARCHAR(25)  
	)  
  
	DECLARE @TB_BATCH	TABLE   
	(  
		 SEQ			INT  
		,DIV_CD			NVARCHAR(10)  
		,PLANT_CD		NVARCHAR(10)  
		,REQ_DT			NVARCHAR(7)  
		,REQ_NO			NVARCHAR(20)  
		,REQ_SEQ		INT  
		,WC_CD			NVARCHAR(10)  
		,LINE_CD		NVARCHAR(20)  
		,PLAN_SEQ		INT  
		,BATCH_NO		INT  
		,ITEM_TYPE		NVARCHAR(10)  
		,USEM_QTY		NUMERIC(15,4)  
		,SU_REQ_NO		NVARCHAR(50)  
		,ZMESIFNO		NVARCHAR(25)  
	)  
  
	DECLARE  @DC_I				INT  
			,@DC_CNT_IF			INT  
	  
	DECLARE  @DC_ZMESIFNO		NVARCHAR(25)  
			,@DC_DEL_ZMESIFNO	NVARCHAR(25)  
  
	DECLARE  @DC_LOT_NO			NVARCHAR(50)  
			,@DC_MAX_GROUP_SEQ	INT  
	  
	SELECT @DC_LOT_NO = LOT_NO  
	FROM PD_RESULT (NOLOCK)  
	WHERE DIV_CD = @DIV_CD  
	 AND PLANT_CD = @PLANT_CD  
	 AND ORDER_NO = @ORDER_NO  
	 AND PROC_NO = @PROC_NO  
	 AND REVISION = @REVISION   
	 AND ORDER_TYPE = @ORDER_TYPE   
	 AND ORDER_FORM = @ORDER_FORM   
	 AND ROUT_NO = @ROUT_NO   
	 AND ROUT_VER = @ROUT_VER   
	 AND WC_CD = @WC_CD  
	 AND LINE_CD = @LINE_CD   
	 AND PROC_CD = @PROC_CD   
	 AND S_CHK = @S_CHK  
	 AND RESULT_SEQ = @RESULT_SEQ  
  
	IF EXISTS ( SELECT DIV_CD  
				FROM PD_RESULT (NOLOCK)  
				WHERE DIV_CD = @DIV_CD  
				 AND PLANT_CD = @PLANT_CD  
				 AND ORDER_NO = @ORDER_NO  
				 AND PROC_NO = @PROC_NO  
				 AND REVISION = @REVISION   
				 AND ORDER_TYPE = @ORDER_TYPE   
				 AND ORDER_FORM = @ORDER_FORM   
				 AND ROUT_NO = @ROUT_NO   
				 AND ROUT_VER = @ROUT_VER   
				 AND WC_CD = @WC_CD  
				 AND LINE_CD = @LINE_CD   
				 AND PROC_CD = @PROC_CD   
				 AND S_CHK = @S_CHK  
				 AND RESULT_SEQ = @RESULT_SEQ  
				 AND GROUP_LOT <> '*'  
				 AND GROUP_LOT <> ''  
				 AND GROUP_LOT IS NOT NULL)  
	BEGIN  
		INSERT INTO @TB_DELETE_RESULT  
		(  
			 DIV_CD			,PLANT_CD		,PROC_NO		,ORDER_NO		,REVISION  
			,ORDER_TYPE		,ORDER_FORM		,ROUT_NO		,ROUT_VER		,WC_CD  
			,LINE_CD		,PROC_CD		,S_CHK			,RESULT_SEQ		,LOT_SEQ		  
			,SIL_DT			,OUT_CHK		,GROUP_SEQ  
		)  
		SELECT  
			 B.DIV_CD		,B.PLANT_CD		,B.PROC_NO		,B.ORDER_NO		,B.REVISION  
			,B.ORDER_TYPE	,B.ORDER_FORM	,B.ROUT_NO		,B.ROUT_VER		,B.WC_CD  
			,B.LINE_CD		,B.PROC_CD		,B.S_CHK		,B.RESULT_SEQ	,B.LOT_SEQ  
			,B.SIL_DT		,C.OUT_CHK		,C.GROUP_SEQ  
		FROM PD_RESULT A (NOLOCK)   
		INNER JOIN PD_RESULT B (NOLOCK)  
		 ON A.DIV_CD = B.DIV_CD  
		 AND A.PLANT_CD = B.PLANT_CD  
		 AND A.PROC_NO = B.PROC_NO   
		 AND A.GROUP_LOT = B.GROUP_LOT   
		INNER JOIN PD_ORDER_PROC C (NOLOCK)  
		 ON B.DIV_CD = C.DIV_CD  
		 AND B.PLANT_CD = C.PLANT_CD  
		 AND B.WC_CD = C.WC_CD  
		 AND B.LINE_CD = C.LINE_CD  
		 AND B.PROC_NO = C.PROC_NO   
		 AND B.PROC_CD = C.PROC_CD   
		WHERE A.DIV_CD = @DIV_CD  
		 AND A.PLANT_CD = @PLANT_CD  
		 AND A.ORDER_NO = @ORDER_NO  
		 AND A.PROC_NO = @PROC_NO  
		 AND A.REVISION = @REVISION   
		 AND A.ORDER_TYPE = @ORDER_TYPE   
		 AND A.ORDER_FORM = @ORDER_FORM   
		 AND A.ROUT_NO = @ROUT_NO   
		 AND A.ROUT_VER = @ROUT_VER   
		 AND A.WC_CD = @WC_CD  
		 AND A.LINE_CD = @LINE_CD   
		 AND A.PROC_CD = @PROC_CD   
		 AND A.S_CHK = @S_CHK  
		 AND A.RESULT_SEQ = @RESULT_SEQ  
	END  
	ELSE  
	BEGIN  
		INSERT INTO @TB_DELETE_RESULT  
		(  
			 DIV_CD			,PLANT_CD		,PROC_NO		,ORDER_NO		,REVISION  
			,ORDER_TYPE		,ORDER_FORM		,ROUT_NO		,ROUT_VER		,WC_CD  
			,LINE_CD		,PROC_CD		,S_CHK			,RESULT_SEQ		,LOT_SEQ	  
			,SIL_DT			,OUT_CHK		,GROUP_SEQ  
		)  
		SELECT  
			 A.DIV_CD		,A.PLANT_CD		,A.PROC_NO		,A.ORDER_NO		,A.REVISION  
			,A.ORDER_TYPE	,A.ORDER_FORM	,A.ROUT_NO		,A.ROUT_VER		,A.WC_CD  
			,A.LINE_CD		,A.PROC_CD		,A.S_CHK		,A.RESULT_SEQ	,A.LOT_SEQ  
			,A.SIL_DT		,B.OUT_CHK		,B.GROUP_SEQ  
		FROM PD_RESULT A (NOLOCK)  
		INNER JOIN PD_ORDER_PROC B (NOLOCK)  
		 ON A.DIV_CD = B.DIV_CD  
		 AND A.PLANT_CD = B.PLANT_CD  
		 AND A.PROC_NO = B.PROC_NO  
		 AND A.ORDER_NO = B.ORDER_NO  
		 AND A.REVISION = B.REVISION  
		 AND A.ORDER_TYPE = B.ORDER_TYPE  
		 AND A.ORDER_FORM = B.ORDER_FORM  
		 AND A.ROUT_NO = B.ROUT_NO  
		 AND A.ROUT_VER = B.ROUT_VER  
		 AND A.WC_CD = B.WC_CD  
		 AND A.LINE_CD = B.LINE_CD  
		 AND A.PROC_CD = B.PROC_CD  
		WHERE A.DIV_CD = @DIV_CD  
		 AND A.PLANT_CD = @PLANT_CD  
		 AND A.ORDER_NO = @ORDER_NO  
		 AND A.PROC_NO = @PROC_NO  
		 AND A.REVISION = @REVISION   
		 AND A.ORDER_TYPE = @ORDER_TYPE   
		 AND A.ORDER_FORM = @ORDER_FORM   
		 AND A.ROUT_NO = @ROUT_NO   
		 AND A.ROUT_VER = @ROUT_VER   
		 AND A.WC_CD = @WC_CD  
		 AND A.LINE_CD = @LINE_CD   
		 AND A.PROC_CD = @PROC_CD   
		 AND A.S_CHK = @S_CHK  
		 AND A.RESULT_SEQ = @RESULT_SEQ		  
	END  
  
	SELECT TOP 1 @DC_MAX_GROUP_SEQ = GROUP_SEQ  
	FROM @TB_DELETE_RESULT  
	ORDER BY GROUP_SEQ DESC  
  
	-------체킹  
	IF @S_CHK = 'Y'  
	BEGIN  
		SET @MSG_CD = '0060'      
		SET @MSG_DETAIL = '일지실적은 현재화면에서 삭제할 수 없습니다.'   
		RETURN 1  
	END  
	 
	IF EXISTS(  SELECT A.DIV_CD    
				FROM PD_RESULT A (NOLOCK)   
				INNER JOIN @TB_DELETE_RESULT B   
				 ON A.DIV_CD = B.DIV_CD   
				 AND A.PLANT_CD = B.PLANT_CD   
				 AND A.PROC_NO = B.PROC_NO   
				 AND A.ORDER_NO = B.ORDER_NO   
				 AND A.REVISION = B.REVISION   
				 AND A.ORDER_TYPE = B.ORDER_TYPE   
				 AND A.ORDER_FORM = B.ORDER_FORM   
				 AND A.ROUT_NO = B.ROUT_NO   
				 AND A.ROUT_VER = B.ROUT_VER   
				 AND A.WC_CD = B.WC_CD   
				 AND A.LINE_CD = B.LINE_CD   
				 AND A.PROC_CD = B.PROC_CD   
				 AND A.RESULT_SEQ = B.RESULT_SEQ  
				 AND A.S_CHK = B.S_CHK   
				 AND A.EDATE IS NULL)   
	BEGIN  
		SET @MSG_CD = '0060'      
		SET @MSG_DETAIL = '현재 작업진행 중인 실적이 있습니다. 삭제할 수 없습니다.'   
		RETURN 1   
	END  
 
	IF @DC_LOT_NO NOT LIKE 'PR%'  
	BEGIN  
		--IF EXISTS(  SELECT A.DIV_CD    
		--			FROM PD_RESULT A (NOLOCK)   
		--			INNER JOIN @TB_DELETE_RESULT B   
		--			 ON A.DIV_CD = B.DIV_CD   
		--			 AND A.PLANT_CD = B.PLANT_CD   
		--			 AND A.PROC_NO = B.PROC_NO   
		--			 AND A.ORDER_NO = B.ORDER_NO   
		--			 AND A.REVISION = B.REVISION   
		--			 AND A.ORDER_TYPE = B.ORDER_TYPE   
		--			 AND A.ORDER_FORM = B.ORDER_FORM   
		--			 AND A.ROUT_NO = B.ROUT_NO   
		--			 AND A.ROUT_VER = B.ROUT_VER   
		--			 AND A.WC_CD = B.WC_CD   
		--			 AND A.LINE_CD = B.LINE_CD   
		--			 AND A.PROC_CD = B.PROC_CD   
		--			 AND A.RESULT_SEQ = B.RESULT_SEQ  
		--			 AND A.S_CHK = B.S_CHK   
		--			 AND A.EDATE IS NULL)   
		--BEGIN  
		--	SET @MSG_CD = '0060'      
		--	SET @MSG_DETAIL = '현재 작업진행 중인 실적이 있습니다. 삭제할 수 없습니다.'   
		--	RETURN 1   
		--END  
  
		IF EXISTS(	SELECT DIV_CD  
					FROM PD_RESULT (NOLOCK)  
					WHERE DIV_CD = @DIV_CD  
					  AND PLANT_CD = @PLANT_CD  
					  AND PROC_NO = @PROC_NO  
					  AND ORDER_NO = @ORDER_NO  
					  AND REVISION = @REVISION  
					  AND ORDER_TYPE = @ORDER_TYPE  
					  AND ORDER_FORM = @ORDER_FORM  
					  AND ROUT_NO = @ROUT_NO  
					  AND ROUT_VER = @ROUT_VER  
					  AND WC_CD = @WC_CD  
					  AND LINE_CD = @LINE_CD  
					  AND PROC_CD = @PROC_CD  
					  AND RESULT_SEQ > @RESULT_SEQ  
					  AND PROC_CD NOT IN ('AI','RI')  
					  AND S_CHK = 'N')  
		BEGIN   
			SET @MSG_CD = '0060'      
			SET @MSG_DETAIL = '다음실적이 존재합니다. 실적삭제할 수 없습니다.'   
			RETURN 1   
		END  
  
		IF EXISTS(  SELECT A.DIV_CD    
					FROM PD_RESULT A (NOLOCK)   
					INNER JOIN @TB_DELETE_RESULT B   
					 ON A.DIV_CD = B.DIV_CD   
					 AND A.PLANT_CD = B.PLANT_CD   
					 AND A.PROC_NO = B.PROC_NO   
					 AND A.ORDER_NO = B.ORDER_NO   
					 AND A.REVISION = B.REVISION   
					 AND A.ORDER_TYPE = B.ORDER_TYPE   
					 AND A.ORDER_FORM = B.ORDER_FORM   
					 AND A.ROUT_NO = B.ROUT_NO   
					 AND A.ROUT_VER = B.ROUT_VER   
					 AND A.WC_CD = B.WC_CD   
					 AND A.LINE_CD = B.LINE_CD   
					 AND A.PROC_CD = B.PROC_CD   
					 AND A.RESULT_SEQ > B.RESULT_SEQ  
					 AND A.S_CHK = B.S_CHK  
					 AND GROUP_LOT <> '*'  
					 AND GROUP_LOT <> ''  
					 AND GROUP_LOT IS NOT NULL)  
		BEGIN  
			SET @MSG_CD = '0060'      
			SET @MSG_DETAIL = '그룹내에 순번이 맞지 않습니다. 임시LOT 확인요망'   
			RETURN 1   
		END  
  
		IF EXISTS ( SELECT A.DIV_CD  
					FROM PD_RESULT_PACKING_HDR A (NOLOCK)  
					INNER JOIN @TB_DELETE_RESULT B  
					 ON A.DIV_CD = B.DIV_CD  
					 AND A.PLANT_CD = B.PLANT_CD  
					 AND A.ORDER_NO = B.ORDER_NO  
					 AND A.REVISION = B.REVISION  
					 AND A.WC_CD = B.WC_CD  
					 AND A.LINE_CD = B.LINE_CD  
					 AND A.RESULT_SEQ = B.RESULT_SEQ  
					WHERE A.DIV_CD = @DIV_CD  
					  AND A.PLANT_CD = @PLANT_CD  
					  AND A.LOT_NO = @DC_LOT_NO)  
		BEGIN  
			SET @MSG_CD = '0060'  
			SET @MSG_DETAIL = '이미 출하 포장된 내역입니다. 삭제할 수 없습니다.'  
			RETURN 1  
		END  
  
		IF EXISTS(  SELECT A.DIV_CD  
					FROM PD_USEM A (NOLOCK)  
					INNER JOIN PD_ORDER_PROC B (NOLOCK)  
					 ON A.DIV_CD = B.DIV_CD  
					 AND A.PLANT_CD = B.PLANT_CD  
					 AND A.PROC_NO = B.PROC_NO  
					 AND A.ORDER_NO = B.ORDER_NO  
					 AND A.REVISION = B.REVISION  
					 AND A.ORDER_TYPE = B.ORDER_TYPE  
					 AND A.ORDER_FORM = B.ORDER_FORM  
					 AND A.ROUT_NO = B.ROUT_NO  
					 AND A.ROUT_VER = B.ROUT_VER  
					 AND A.WC_CD = B.WC_CD  
					 AND A.LINE_CD = B.LINE_CD  
					 AND A.PROC_CD = B.PROC_CD  
					WHERE A.DIV_CD = @DIV_CD  
					  AND A.PLANT_CD = @PLANT_CD  
					  AND A.PROC_NO = @PROC_NO  
					  AND A.ORDER_NO = @ORDER_NO  
					  AND A.REVISION = @REVISION  
					  AND A.ORDER_TYPE = @ORDER_TYPE  
					  AND A.ORDER_FORM = @ORDER_FORM  
					  AND A.ROUT_NO = @ROUT_NO  
					  AND A.ROUT_VER = @ROUT_VER  
					  AND A.WC_CD = @WC_CD  
					  AND A.LINE_CD = @LINE_CD  
					  AND B.GROUP_SEQ > @DC_MAX_GROUP_SEQ  
					  AND A.LOT_NO = @DC_LOT_NO  
					  AND A.BE_ORDER_NO = @ORDER_NO  
					  AND A.BE_REVISION = @REVISION  
					  AND A.BE_RESULT_SEQ = @RESULT_SEQ  
					  AND A.BE_PROC_CD = @PROC_CD )  
		BEGIN  
			SET @MSG_CD = '0060'  
			SET @MSG_DETAIL = '해당 LOT NO로 투입된 내역이 있습니다. 삭제할 수 없습니다.'  
			RETURN 1  
		END  
  
		IF EXISTS ( SELECT A.DIV_CD  
					FROM @TB_DELETE_RESULT A  
					INNER JOIN QC_PQC_ORDER B (NOLOCK)  
					 ON A.DIV_CD = B.DIV_CD   
					 AND A.PLANT_CD = B.PLANT_CD   
					 AND A.PROC_NO = B.PROC_NO   
					 AND A.ORDER_NO = B.ORDER_NO   
					 AND A.REVISION = B.REVISION   
					 AND A.ORDER_TYPE = B.ORDER_TYPE   
					 AND A.ORDER_FORM = B.ORDER_FORM   
					 AND A.ROUT_NO = B.ROUT_NO   
					 AND A.ROUT_VER = B.ROUT_VER   
					 AND A.WC_CD = B.WC_CD   
					 AND A.LINE_CD = B.LINE_CD   
					 AND A.PROC_CD = B.PROC_CD   
					 AND A.RESULT_SEQ = B.RESULT_SEQ  
					 AND A.S_CHK = B.S_CHK  
					WHERE B.QC_RESULT <> ''  
					  AND B.QC_RESULT IS NOT NULL)  
		BEGIN  
			SET @MSG_CD = '0060'  
			SET @MSG_DETAIL = '판정 내역이 존재합니다. 삭제할 수 없습니다.'  
			RETURN 1  
		END 
 
		----연번체크 
		--IF EXISTS ( SELECT A.DIV_CD 
		--			FROM 
		--			( 
		--				SELECT B.DIV_CD 
		--					  ,B.PLANT_CD 
		--					  ,B.DT 
		--					  ,B.WC_CD 
		--					  ,B.LINE_CD 
		--					  ,B.PROC_CD 
		--					  ,B.LOT_SEQ 
		--				FROM PD_LOT_SEQ A (NOLOCK) 
		--				INNER JOIN 
		--				( 
		--					SELECT A.DIV_CD 
		--						  ,A.PLANT_CD 
		--						  ,LEFT(A.SIL_DT,7) AS DT 
		--						  ,A.WC_CD 
		--						  ,A.LINE_CD 
		--						  ,A.PROC_CD 
		--						  ,MAX(A.LOT_SEQ) AS LOT_SEQ 
		--					FROM @TB_DELETE_RESULT A 
		--					INNER JOIN PD_RESULT B (NOLOCK) 
		--					 ON A.DIV_CD = B.DIV_CD   
		--					 AND A.PLANT_CD = B.PLANT_CD   
		--					 AND A.PROC_NO = B.PROC_NO   
		--					 AND A.ORDER_NO = B.ORDER_NO   
		--					 AND A.REVISION = B.REVISION   
		--					 AND A.ORDER_TYPE = B.ORDER_TYPE   
		--					 AND A.ORDER_FORM = B.ORDER_FORM   
		--					 AND A.ROUT_NO = B.ROUT_NO   
		--					 AND A.ROUT_VER = B.ROUT_VER   
		--					 AND A.WC_CD = B.WC_CD   
		--					 AND A.LINE_CD = B.LINE_CD   
		--					 AND A.PROC_CD = B.PROC_CD   
		--					 AND A.RESULT_SEQ = B.RESULT_SEQ  
		--					 AND A.S_CHK = B.S_CHK  
		--					WHERE A.OUT_CHK = 'Y' 
		--					  AND ISNULL(B.J_CHK,'N') = 'N' 
		--					GROUP BY A.DIV_CD, A.PLANT_CD, LEFT(A.SIL_DT,7), A.WC_CD, A.LINE_CD, A.PROC_CD 
		--				) B 
		--				 ON A.DIV_CD = B.DIV_CD 
		--				 AND A.PLANT_CD = B.PLANT_CD 
		--				 AND A.DT = B.DT 
		--				 AND A.WC_CD = B.WC_CD 
		--				 AND A.LINE_CD = B.LINE_CD 
		--				 AND A.PROC_CD = B.PROC_CD 
		--			) A 
		--			INNER JOIN 
		--			( 
		--				SELECT B.DIV_CD 
		--					  ,B.PLANT_CD 
		--					  ,B.DT 
		--					  ,B.WC_CD 
		--					  ,B.LINE_CD 
		--					  ,B.PROC_CD 
		--					  ,B.LOT_SEQ 
		--				FROM PD_LOT_SEQ A (NOLOCK) 
		--				INNER JOIN 
		--				( 
		--					SELECT A.DIV_CD 
		--						  ,A.PLANT_CD 
		--						  ,LEFT(A.SIL_DT,7) AS DT 
		--						  ,A.WC_CD 
		--						  ,A.LINE_CD 
		--						  ,A.PROC_CD 
		--						  ,MAX(A.LOT_SEQ) AS LOT_SEQ 
		--					FROM PD_RESULT A (NOLOCK) 
		--					INNER JOIN PD_ORDER_PROC B (NOLOCK)  
		--					 ON A.DIV_CD = B.DIV_CD 
		--					 AND A.PLANT_CD = B.PLANT_CD 
		--					 AND A.PROC_NO = B.PROC_NO 
		--					 AND A.ORDER_NO = B.ORDER_NO 
		--					 AND A.REVISION = B.REVISION 
		--					 AND A.ORDER_TYPE = B.ORDER_TYPE 
		--					 AND A.ORDER_FORM = B.ORDER_FORM 
		--					 AND A.ROUT_NO = B.ROUT_NO 
		--					 AND A.ROUT_VER = B.ROUT_VER 
		--					 AND A.WC_CD = B.WC_CD 
		--					 AND A.LINE_CD = B.LINE_CD 
		--					 AND A.PROC_CD = B.PROC_CD 
		--					WHERE B.OUT_CHK = 'Y' 
		--					  AND ISNULL(A.J_CHK,'N') = 'N' 
		--					GROUP BY A.DIV_CD, A.PLANT_CD, LEFT(A.SIL_DT,7), A.WC_CD, A.LINE_CD, A.PROC_CD 
		--				) B 
		--				 ON A.DIV_CD = B.DIV_CD 
		--				 AND A.PLANT_CD = B.PLANT_CD 
		--				 AND A.DT = B.DT 
		--				 AND A.WC_CD = B.WC_CD 
		--				 AND A.LINE_CD = B.LINE_CD 
		--				 AND A.PROC_CD = B.PROC_CD 
		--			) B 
		--			 ON A.DIV_CD = B.DIV_CD 
		--			 AND A.PLANT_CD = B.PLANT_CD 
		--			 AND A.DT = B.DT 
		--			 AND A.WC_CD = B.WC_CD 
		--			 AND A.LINE_CD = B.LINE_CD 
		--			 AND A.PROC_CD = B.PROC_CD 
		--			WHERE B.LOT_SEQ > A.LOT_SEQ) 
		--BEGIN  
		--	SET @MSG_CD = '0060'      
		--	SET @MSG_DETAIL = '연번을 확인하세요.(선택하신 LOT연번보다 더 큰 연번이 존재합니다.)' 
		--	RETURN 1  
		--END 
	END 
	-------체킹 끝  
  
 
 	--이력저장  
	INSERT INTO PD_RESULT_DELETE_HISTORY  
	(  
		 DIV_CD			,PLANT_CD		,PROC_NO		,ORDER_NO  
		,REVISION		,ORDER_TYPE		,ORDER_FORM		,ROUT_NO  
		,ROUT_VER		,WC_CD			,LINE_CD		,PROC_CD  
		,S_CHK			,RESULT_SEQ		,ITEM_CD		,LOT_NO  
		,LOT_SEQ		,RESULT_QTY		,GOOD_QTY		,BAD_QTY  
		,GROUP_LOT		,GROUP_YN		,EQP_CD			,SDATE  
		,EDATE			,SIL_DT			,ZMESIFNO  
		,INSERT_ID		,INSERT_DT		,LOT_SEQ_UPDATE  
	)  
	SELECT  
		 B.DIV_CD		,B.PLANT_CD		,B.PROC_NO		,B.ORDER_NO  
		,B.REVISION		,B.ORDER_TYPE	,B.ORDER_FORM	,B.ROUT_NO  
		,B.ROUT_VER		,B.WC_CD		,B.LINE_CD		,B.PROC_CD  
		,B.S_CHK		,B.RESULT_SEQ	,B.ITEM_CD		,B.LOT_NO  
		,B.LOT_SEQ		,B.RESULT_QTY	,B.GOOD_QTY		,B.BAD_QTY  
		,B.GROUP_LOT	,B.GROUP_YN		,B.EQP_CD		,B.SDATE  
		,B.EDATE		,B.SIL_DT		,B.ZMESIFNO  
		,@USER_ID		,GETDATE()		,CASE WHEN ISNULL(C.LOT_SEQ,0) = A.LOT_SEQ AND A.LOT_SEQ > 0 THEN C.LOT_SEQ - 1 ELSE C.LOT_SEQ END  
	FROM @TB_DELETE_RESULT A  
	INNER JOIN PD_RESULT B (NOLOCK)  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.PROC_NO = B.PROC_NO  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND A.PROC_CD = B.PROC_CD  
	 AND A.S_CHK = B.S_CHK  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	LEFT OUTER JOIN PD_LOT_SEQ C   
	 ON A.DIV_CD = C.DIV_CD  
	 AND A.PLANT_CD = C.PLANT_CD  
	 AND LEFT(A.SIL_DT,2) + LEFT(SUBSTRING(@DC_LOT_NO,2,4),2) + '-' + RIGHT(SUBSTRING(@DC_LOT_NO,2,4),2) = C.DT  
	 AND A.WC_CD = C.WC_CD  
	 AND A.LINE_CD = C.LINE_CD  
	 AND A.PROC_CD = C.PROC_CD  
	 AND A.OUT_CHK = 'Y'  
  
	-------데이터 삭제  
	--배정업데이트  
	DECLARE  @DC_CNT_BATCH		INT  
			,@DC_USEM_QTY		NUMERIC(15,4)  
			,@DC_SU_REQ_NO		NVARCHAR(50)  
	  
	INSERT INTO @TB_BATCH  
	(  
		 SEQ  
		,DIV_CD			,PLANT_CD		,REQ_DT			,REQ_NO  
		,REQ_SEQ		,WC_CD			,LINE_CD		,PLAN_SEQ  
		,BATCH_NO		,ITEM_TYPE		,USEM_QTY		,SU_REQ_NO  
		,ZMESIFNO  
	)  
	SELECT  
		 ROW_NUMBER() OVER(ORDER BY (SELECT 1))  
		,A.DIV_CD		,A.PLANT_CD		,A.REQ_DT		,A.REQ_NO  
		,A.REQ_SEQ		,A.WC_CD		,A.LINE_CD		,A.PLAN_SEQ  
		,A.BATCH_NO		,A.ITEM_TYPE	,B.USEM_QTY		,A.SU_REQ_NO  
		,A.ZMESIFNO  
	FROM MT_ITEM_OUT_BATCH A (NOLOCK)   
	INNER JOIN PD_USEM B (NOLOCK)   
	 ON A.DIV_CD = B.DIV_CD   
	 AND A.PLANT_CD = B.PLANT_CD   
	 AND A.REQ_DT = B.REQ_DT   
	 AND A.REQ_NO = B.REQ_NO   
	 AND A.REQ_SEQ = B.REQ_SEQ   
	 AND A.LINE_CD = B.LINE_CD   
	 AND A.WC_CD = B.WC_CD   
	 AND A.PLAN_SEQ = B.PLAN_SEQ   
	 AND A.BATCH_NO = B.BATCH_NO   
	 AND A.ITEM_TYPE = B.ITEM_TYPE   
	 --AND A.ST_TYPE = B.REWORK_FLG  ---나중에 확인  
	 AND A.LOT_NO = B.LOT_NO   
	INNER JOIN @TB_DELETE_RESULT C   
	 ON B.DIV_CD = C.DIV_CD   
	 AND B.PLANT_CD = C.PLANT_CD   
	 AND B.PROC_NO = C.PROC_NO   
	 AND B.ORDER_NO = C.ORDER_NO   
	 AND B.REVISION = C.REVISION   
	 AND B.ORDER_TYPE = C.ORDER_TYPE   
	 AND B.ORDER_FORM = C.ORDER_FORM   
	 AND B.ROUT_NO = C.ROUT_NO   
	 AND B.ROUT_VER = C.ROUT_VER   
	 AND B.WC_CD = C.WC_CD   
	 AND B.LINE_CD = C.LINE_CD   
	 AND B.PROC_CD = C.PROC_CD   
	 AND B.RESULT_SEQ = C.RESULT_SEQ  
	  
	SET @DC_I = 0  
	SELECT @DC_CNT_BATCH = COUNT(*) FROM @TB_BATCH  
  
	WHILE(1=1)  
	BEGIN  
		SET @DC_I = @DC_I + 1  
		  
		SET @DC_ZMESIFNO = ''  
  
		SELECT @DC_ZMESIFNO = ZMESIFNO  
			  ,@DC_USEM_QTY = USEM_QTY  
			  ,@DC_SU_REQ_NO = SU_REQ_NO  
		FROM @TB_BATCH  
		WHERE SEQ = @DC_I  
  
		IF (SELECT ITEM_TYPE FROM @TB_BATCH WHERE SEQ = @DC_I) = 'SU'  
		BEGIN  
			--SAP I/F 삭제  
			EXEC USP_SAP_MESIFNO_CREATE @DIV_CD, @PLANT_CD, 'P020', @USER_ID, @DC_DEL_ZMESIFNO OUT      
      
			INSERT INTO SAP_Z02MESF_P020      
			(  
				 CSYST		,ZMESIFNO			,WERKS			,AUFNR  
				,DAUAT		,VERID				,ARBPL			,PRODMAT  
				,RSNUM		,RSPOS				,COMMAT			,ZLOTNO  
				,CHARG		,ZREGQ				,MEINS			,BASEM  
				,ZSEQL		,ZSEQA				,BGUBUN			,ZGIOP  
				,ZVAART		,ZSTORN				,ZMESIFNO_C		,ZCRES  
				,ZGI		,RETCD				,RETMG  
				,MES_INS_DT	,MES_INS_ID			,MES_UPD_DT		,MES_UPD_ID  
			)  
			SELECT DISTINCT      
				 CSYST		,@DC_DEL_ZMESIFNO	,WERKS			,AUFNR  
				,DAUAT		,VERID				,ARBPL			,PRODMAT  
				,RSNUM		,RSPOS				,COMMAT			,ZLOTNO  
				,CHARG		,ZREGQ				,MEINS			,BASEM  
				,ZSEQL		,ZSEQA				,BGUBUN			,ZGIOP  
				,'R'		,'C'				,ZMESIFNO		,ZCRES  
				,ZGI		,NULL				,NULL  
				,GETDATE()	,@USER_ID			,NULL			,NULL      
			FROM SAP_Z02MESF_P020 (NOLOCK)      
			WHERE ZMESIFNO = @DC_ZMESIFNO  
			--SAP I/F 삭제 끝  
			  
			--가배정 업데이트  
			UPDATE MT_ITEM_OUT_BATCH_SU  
			SET  USE_QTY = USE_QTY - @DC_USEM_QTY  
				,USE_FLG = CASE WHEN REQ_QTY <= USE_QTY - @DC_USEM_QTY THEN 'N' ELSE 'Y' END   
				,UPDATE_ID = @USER_ID   
				,UPDATE_DT = GETDATE()  
			WHERE DIV_CD = @DIV_CD  
			  AND PLANT_CD = @PLANT_CD  
			  AND REQ_NO = @DC_SU_REQ_NO  
  
			--진배정 삭제  
			UPDATE A  
			SET A.CHG_RSN = '06'  
			FROM MT_ITEM_OUT_BATCH A  
			INNER JOIN  
			(  
				SELECT DIV_CD  
					  ,PLANT_CD  
					  ,REQ_DT  
					  ,REQ_NO  
					  ,REQ_SEQ  
					  ,WC_CD  
					  ,LINE_CD  
					  ,PLAN_SEQ  
					  ,BATCH_NO  
					  ,ITEM_TYPE  
				FROM @TB_BATCH  
				WHERE SEQ = @DC_I  
			) B  
			 ON A.DIV_CD = B.DIV_CD  
			 AND A.PLANT_CD = B.PLANT_CD  
			 AND A.REQ_DT = B.REQ_DT  
			 AND A.REQ_NO = B.REQ_NO  
			 AND A.REQ_SEQ = B.REQ_SEQ  
			 AND A.WC_CD = B.WC_CD  
			 AND A.LINE_CD = B.LINE_CD  
			 AND A.PLAN_SEQ = B.PLAN_SEQ  
			 AND A.BATCH_NO = B.BATCH_NO  
			 AND A.ITEM_TYPE = B.ITEM_TYPE  
		END  
		ELSE  
		BEGIN  
			UPDATE A  
			SET  A.USE_QTY = A.USE_QTY - @DC_USEM_QTY  
				,A.USE_FLG = CASE WHEN A.REQ_QTY <= A.USE_QTY - @DC_USEM_QTY THEN 'N' ELSE 'Y' END  
				,A.UPDATE_ID = @USER_ID  
				,A.UPDATE_DT = GETDATE()  
			FROM MT_ITEM_OUT_BATCH A  
			INNER JOIN  
			(  
				SELECT DIV_CD  
					  ,PLANT_CD  
					  ,REQ_DT  
					  ,REQ_NO  
					  ,REQ_SEQ  
					  ,WC_CD  
					  ,LINE_CD  
					  ,PLAN_SEQ  
					  ,BATCH_NO  
					  ,ITEM_TYPE  
				FROM @TB_BATCH  
				WHERE SEQ = @DC_I  
			) B  
			 ON A.DIV_CD = B.DIV_CD  
			 AND A.PLANT_CD = B.PLANT_CD  
			 AND A.REQ_DT = B.REQ_DT  
			 AND A.REQ_NO = B.REQ_NO  
			 AND A.REQ_SEQ = B.REQ_SEQ  
			 AND A.WC_CD = B.WC_CD  
			 AND A.LINE_CD = B.LINE_CD  
			 AND A.PLAN_SEQ = B.PLAN_SEQ  
			 AND A.BATCH_NO = B.BATCH_NO  
			 AND A.ITEM_TYPE = B.ITEM_TYPE  
		END  
  
		IF @DC_I >= @DC_CNT_BATCH BREAK  
	END  
	--배정업데이트 끝  
  
  
	--연번 업데이트  
	UPDATE A   
	SET  A.LOT_SEQ = CASE WHEN ISNULL(A.LOT_SEQ,0) = B.LOT_SEQ AND B.LOT_SEQ > 0 THEN A.LOT_SEQ - 1 ELSE A.LOT_SEQ END   
		,A.UPDATE_ID = @USER_ID   
		,A.UPDATE_DT = GETDATE()   
	FROM PD_LOT_SEQ A (NOLOCK)   
	INNER JOIN @TB_DELETE_RESULT B   
	 ON A.DIV_CD = B.DIV_CD   
	 AND A.PLANT_CD = B.PLANT_CD   
	 AND A.DT = LEFT(B.SIL_DT,2) + LEFT(SUBSTRING(@DC_LOT_NO,2,4),2) + '-' + RIGHT(SUBSTRING(@DC_LOT_NO,2,4),2)  
	 AND A.WC_CD = B.WC_CD   
	 AND A.LINE_CD = B.LINE_CD   
	 AND A.PROC_CD = B.PROC_CD   
	 AND B.OUT_CHK = 'Y'  
	INNER JOIN PD_RESULT RESULT (NOLOCK)  
	 ON B.DIV_CD = RESULT.DIV_CD  
	 AND B.PLANT_CD = RESULT.PLANT_CD  
	 AND B.PROC_NO = RESULT.PROC_NO  
	 AND B.ORDER_NO = RESULT.ORDER_NO  
	 AND B.REVISION = RESULT.REVISION  
	 AND B.ORDER_TYPE = RESULT.ORDER_TYPE  
	 AND B.ORDER_FORM = RESULT.ORDER_FORM  
	 AND B.ROUT_NO = RESULT.ROUT_NO  
	 AND B.ROUT_VER = RESULT.ROUT_VER  
	 AND B.WC_CD = RESULT.WC_CD  
	 AND B.LINE_CD = RESULT.LINE_CD  
	 AND B.PROC_CD = RESULT.PROC_CD  
	 AND B.S_CHK = RESULT.S_CHK  
	 AND B.RESULT_SEQ = RESULT.RESULT_SEQ  
	 AND ISNULL(RESULT.J_CHK,'N') = 'N'  
  
  
	--SAP IF 실적   
	IF EXISTS ( SELECT ZMESIFNO   
				FROM PD_RESULT A (NOLOCK)   
				INNER JOIN @TB_DELETE_RESULT B   
				 ON A.DIV_CD = B.DIV_CD   
				 AND A.PLANT_CD = B.PLANT_CD   
				 AND A.PROC_NO = B.PROC_NO   
				 AND A.ORDER_NO = B.ORDER_NO   
				 AND A.REVISION = B.REVISION   
				 AND A.ORDER_TYPE = B.ORDER_TYPE   
				 AND A.ORDER_FORM = B.ORDER_FORM   
				 AND A.ROUT_NO = B.ROUT_NO   
				 AND A.ROUT_VER = B.ROUT_VER   
				 AND A.WC_CD = B.WC_CD   
				 AND A.LINE_CD = B.LINE_CD   
				 AND A.PROC_CD = B.PROC_CD   
				 AND A.RESULT_SEQ = B.RESULT_SEQ  
				 AND A.S_CHK = B.S_CHK  
				 AND A.ZMESIFNO IS NOT NULL   
				 AND A.ZMESIFNO <> '')   
	BEGIN   
		SET @DC_I = 0   
		SET @DC_CNT_IF = 0   
   
		DELETE FROM @TB_SAP_IF   
   
		INSERT INTO @TB_SAP_IF   
		(  
			 SEQ  
			,ZMESIFNO  
		)  
		SELECT   
			 ROW_NUMBER() OVER(ORDER BY (SELECT 1))  
			,ZMESIFNO   
		FROM PD_RESULT A (NOLOCK)   
		INNER JOIN @TB_DELETE_RESULT B   
		 ON A.DIV_CD = B.DIV_CD   
		 AND A.PLANT_CD = B.PLANT_CD   
		 AND A.PROC_NO = B.PROC_NO   
		 AND A.ORDER_NO = B.ORDER_NO   
		 AND A.REVISION = B.REVISION   
		 AND A.ORDER_TYPE = B.ORDER_TYPE   
		 AND A.ORDER_FORM = B.ORDER_FORM  
		 AND A.ROUT_NO = B.ROUT_NO   
		 AND A.ROUT_VER = B.ROUT_VER   
		 AND A.WC_CD = B.WC_CD   
		 AND A.LINE_CD = B.LINE_CD   
		 AND A.PROC_CD = B.PROC_CD   
		 AND A.RESULT_SEQ = B.RESULT_SEQ  
		 AND A.S_CHK = B.S_CHK  
		 AND A.ZMESIFNO IS NOT NULL   
		 AND A.ZMESIFNO <> ''  
		GROUP BY ZMESIFNO  
		   
		SELECT @DC_CNT_IF = COUNT(*) FROM @TB_SAP_IF   
   
		WHILE(1=1)   
		BEGIN   
			SET @DC_I = @DC_I + 1   
			   
			SELECT @DC_ZMESIFNO = ZMESIFNO FROM @TB_SAP_IF WHERE SEQ = @DC_I   
   
			EXEC USP_SAP_MESIFNO_CREATE @DIV_CD, @PLANT_CD, 'P060', @USER_ID, @DC_DEL_ZMESIFNO OUT   
   
			INSERT INTO SAP_Z02MESF_P060   
			(   
				 CSYST			,ZMESIFNO			,WERKS			,AUFNR			,ZPROD   
				,ZLOTNO			,CHARG				,VERID			,PRODMAT		,ZGRQTY   
				,ZBAG			,ZLOT				,ZBAGN,FBAG		,MEINS			,ZAN   
				,WORKER			,ZVAART				,ZSTORN			,ZMESIFNO_C		,MBLNR   
				,MJAHR			,ZCRES				,ZCONF			,MESSAGE		,PMEMO  
				,RETCD 			,RETMG			  
				,MES_INS_DT		,MES_INS_ID			,MES_UPD_DT		,MES_UPD_ID   
			)   
			SELECT    
				 CSYST			,@DC_DEL_ZMESIFNO	,WERKS			,AUFNR			,ZPROD   
				,ZLOTNO			,CHARG				,VERID			,PRODMAT		,ZGRQTY   
				,ZBAG			,ZLOT				,ZBAGN,FBAG		,MEINS			,ZAN   
				,WORKER			,'R'				,'C'			,ZMESIFNO		,MBLNR   
				,MJAHR			,ZCRES				,ZCONF			,MESSAGE		,PMEMO  
				,NULL 			,NULL			  
				,GETDATE()		,@USER_ID			,NULL			,NULL   
			FROM SAP_Z02MESF_P060 (NOLOCK)   
			WHERE WERKS = @PLANT_CD   
			  AND ZMESIFNO = @DC_ZMESIFNO   
			  AND CSYST = 'MES'   
   
			IF @DC_I >= @DC_CNT_IF BREAK   
		END   
	END   
	--SAP IF 실적 끝   
  
	--실적삭제  
	DELETE FROM A   
	FROM PD_RESULT A (NOLOCK)   
	INNER JOIN @TB_DELETE_RESULT B   
	 ON A.DIV_CD = B.DIV_CD   
	 AND A.PLANT_CD = B.PLANT_CD   
	 AND A.PROC_NO = B.PROC_NO   
	 AND A.ORDER_NO = B.ORDER_NO   
	 AND A.REVISION = B.REVISION   
	 AND A.ORDER_TYPE = B.ORDER_TYPE   
	 AND A.ORDER_FORM = B.ORDER_FORM   
	 AND A.ROUT_NO = B.ROUT_NO   
	 AND A.ROUT_VER = B.ROUT_VER   
	 AND A.WC_CD = B.WC_CD   
	 AND A.LINE_CD = B.LINE_CD   
	 AND A.PROC_CD = B.PROC_CD   
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	 AND A.S_CHK = B.S_CHK  
  
  
	--SAP IF 투입   
	IF EXISTS ( SELECT ZMESIFNO   
				FROM PD_USEM A (NOLOCK)   
				INNER JOIN @TB_DELETE_RESULT B   
				 ON A.DIV_CD = B.DIV_CD   
				 AND A.PLANT_CD = B.PLANT_CD   
				 AND A.PROC_NO = B.PROC_NO   
				 AND A.ORDER_NO = B.ORDER_NO   
				 AND A.REVISION = B.REVISION   
				 AND A.ORDER_TYPE = B.ORDER_TYPE   
				 AND A.ORDER_FORM = B.ORDER_FORM   
				 AND A.ROUT_NO = B.ROUT_NO   
				 AND A.ROUT_VER = B.ROUT_VER   
				 AND A.WC_CD = B.WC_CD   
				 AND A.LINE_CD = B.LINE_CD   
				 AND A.PROC_CD = B.PROC_CD   
				 AND A.RESULT_SEQ = B.RESULT_SEQ   
				 AND A.ZMESIFNO IS NOT NULL   
				 AND A.ZMESIFNO <> '')   
	BEGIN   
		SET @DC_I = 0   
		SET @DC_CNT_IF = 0   
   
		DELETE FROM @TB_SAP_IF   
   
		INSERT INTO @TB_SAP_IF   
		(  
			 SEQ  
			,ZMESIFNO  
		)  
		SELECT  
			 ROW_NUMBER() OVER(ORDER BY (SELECT 1))  
			,ZMESIFNO   
		FROM PD_USEM A (NOLOCK)   
		INNER JOIN @TB_DELETE_RESULT B   
		 ON A.DIV_CD = B.DIV_CD   
		 AND A.PLANT_CD = B.PLANT_CD   
		 AND A.PROC_NO = B.PROC_NO   
		 AND A.ORDER_NO = B.ORDER_NO   
		 AND A.REVISION = B.REVISION   
		 AND A.ORDER_TYPE = B.ORDER_TYPE   
		 AND A.ORDER_FORM = B.ORDER_FORM   
		 AND A.ROUT_NO = B.ROUT_NO   
		 AND A.ROUT_VER = B.ROUT_VER   
		 AND A.WC_CD = B.WC_CD   
		 AND A.LINE_CD = B.LINE_CD   
		 AND A.PROC_CD = B.PROC_CD   
		 AND A.RESULT_SEQ = B.RESULT_SEQ   
		 AND A.ZMESIFNO IS NOT NULL   
		 AND A.ZMESIFNO <> ''  
		GROUP BY ZMESIFNO   
	  
		SELECT @DC_CNT_IF = COUNT(*) FROM @TB_SAP_IF   
   
		WHILE(1=1)   
		BEGIN   
			SET @DC_I = @DC_I + 1   
	  
			SELECT @DC_ZMESIFNO = ZMESIFNO FROM @TB_SAP_IF WHERE SEQ = @DC_I   
   
			EXEC USP_SAP_MESIFNO_CREATE @DIV_CD, @PLANT_CD, 'P030', @USER_ID, @DC_DEL_ZMESIFNO OUT   
   
			INSERT INTO SAP_Z02MESF_P030   
			(   
			 CSYST			,ZMESIFNO			,WERKS				,AUFNR				,ZPROD			,VERID   
			,ARBPL			,PRODMAT			,RSNUM				,RSPOS				,COMMAT			,ZLOTNO   
			,CHARG			,ZGIQTY				,MEINS				,BASEM				,ZSEQL			,ZSEQA   
			,BGUBUN			,ZGIOP				,ZVAART				,ZSTORN				,ZMESIFNO_C		,BWART   
			,MBLNR			,MJAHR				,ZCRES				,ZCONF				,MESSAGE		,RETCD   
			,RETMG   
			,MES_INS_DT		,MES_INS_ID			,MES_UPD_DT			,MES_UPD_ID   
			)   
			SELECT   
			 CSYST			,@DC_DEL_ZMESIFNO	,WERKS				,AUFNR				,ZPROD			,VERID   
			,ARBPL			,PRODMAT			,RSNUM				,RSPOS				,COMMAT			,ZLOTNO   
			,CHARG			,ZGIQTY				,MEINS				,BASEM				,ZSEQL			,ZSEQA   
			,BGUBUN			,ZGIOP				,'R'				,'C'				,ZMESIFNO		,BWART   
			,''				,''					,''					,''					,''				,NULL   
			,NULL   
			,GETDATE()		,@USER_ID			,NULL				,NULL   
			FROM SAP_Z02MESF_P030 (NOLOCK)   
			WHERE WERKS = @PLANT_CD   
			  AND ZMESIFNO = @DC_ZMESIFNO   
			  AND CSYST = 'MES'   
   
			IF @DC_I >= @DC_CNT_IF BREAK   
		END   
	END   
	--SAP IF 투입 끝  
  
	--투입삭제  
 
     /* 선언부 */  
    DECLARE @UDI_DATE      NVARCHAR(20)  = '' 
           ,@UDI_SP        NVARCHAR(100) = 'USP_PRD_010W_DELETE2' 
           ,@UDI_REMARK    NVARCHAR(100) = '실적삭제' 
     
     /* 할당 */  
 
    SET @UDI_DATE = CONVERT(VARCHAR(20),GETDATE(),120) 
    INSERT INTO PD_USEM_DEL_HISTORY  
    SELECT @UDI_DATE, ROW_NUMBER() OVER (ORDER BY A.ORDER_NO, A.RESULT_SEQ, A.USEM_SEQ), @UDI_SP, @UDI_REMARK,@USER_ID, 
    A.* 
    FROM PD_USEM A (NOLOCK)  
	INNER JOIN @TB_DELETE_RESULT B  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.PROC_NO = B.PROC_NO  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND A.PROC_CD = B.PROC_CD  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
  
 
	DELETE FROM A  
	FROM PD_USEM A (NOLOCK)  
	INNER JOIN @TB_DELETE_RESULT B  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.PROC_NO = B.PROC_NO  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND A.PROC_CD = B.PROC_CD  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
  
	--라벨삭제  
	IF EXISTS ( SELECT DIV_CD  
				FROM @TB_DELETE_RESULT A  
				WHERE DBO.FN_GET_LAST_PROC(A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.PROC_CD) = 'Y')  
	BEGIN  

        SET @UDI_DATE = CONVERT(VARCHAR(20),GETDATE(),120)  

        INSERT INTO PD_ITEM_IN_DEL_HISTORY
        SELECT @UDI_DATE, 1, @UDI_SP, @UDI_REMARK + '-1', @USER_ID, B.*
		FROM @TB_DELETE_RESULT A  
		INNER JOIN PD_ITEM_IN B (NOLOCK)  
		 ON A.DIV_CD = B.DIV_CD  
		 AND A.PLANT_CD = B.PLANT_CD  
		 AND A.PROC_NO = B.PROC_NO  
		 AND A.ORDER_NO = B.ORDER_NO  
		 AND A.REVISION = B.REVISION  
		 AND A.ORDER_TYPE = B.ORDER_TYPE  
		 AND A.ORDER_FORM = B.ORDER_FORM  
		 AND A.ROUT_NO = B.ROUT_NO  
		 AND A.ROUT_VER = B.ROUT_VER  
		 AND A.WC_CD = B.WC_CD  
		 AND A.LINE_CD = B.LINE_CD  
		 AND CASE WHEN DBO.FN_GET_LAST_PROC(A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.PROC_CD) = 'Y' THEN '*' ELSE A.PROC_CD END = B.PROC_CD  
		 AND A.RESULT_SEQ = B.RESULT_SEQ  
		 AND A.S_CHK = B.S_CHK  
		INNER JOIN PALLET_MASTER C (NOLOCK)  
		 ON B.LOT_NO = C.LOT_NO  

		DELETE C  
		FROM @TB_DELETE_RESULT A  
		INNER JOIN PD_ITEM_IN B (NOLOCK)  
		 ON A.DIV_CD = B.DIV_CD  
		 AND A.PLANT_CD = B.PLANT_CD  
		 AND A.PROC_NO = B.PROC_NO  
		 AND A.ORDER_NO = B.ORDER_NO  
		 AND A.REVISION = B.REVISION  
		 AND A.ORDER_TYPE = B.ORDER_TYPE  
		 AND A.ORDER_FORM = B.ORDER_FORM  
		 AND A.ROUT_NO = B.ROUT_NO  
		 AND A.ROUT_VER = B.ROUT_VER  
		 AND A.WC_CD = B.WC_CD  
		 AND A.LINE_CD = B.LINE_CD  
		 AND CASE WHEN DBO.FN_GET_LAST_PROC(A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.PROC_CD) = 'Y' THEN '*' ELSE A.PROC_CD END = B.PROC_CD  
		 AND A.RESULT_SEQ = B.RESULT_SEQ  
		 AND A.S_CHK = B.S_CHK  
		INNER JOIN PALLET_MASTER C (NOLOCK)  
		 ON B.LOT_NO = C.LOT_NO  
	END  
  
	--수불삭제  

    SET @UDI_DATE = CONVERT(VARCHAR(20),GETDATE(),120)  

    INSERT INTO PD_ITEM_IN_DEL_HISTORY
    SELECT @UDI_DATE, 1, @UDI_SP, @UDI_REMARK + '-2', @USER_ID, B.*
	FROM @TB_DELETE_RESULT A  
	INNER JOIN PD_ITEM_IN B  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.PROC_NO = B.PROC_NO  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND CASE WHEN DBO.FN_GET_LAST_PROC(A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.PROC_CD) = 'Y' THEN '*' ELSE A.PROC_CD END = B.PROC_CD  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	 AND A.S_CHK = B.S_CHK  


	DELETE B  
	FROM @TB_DELETE_RESULT A  
	INNER JOIN PD_ITEM_IN B  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.PROC_NO = B.PROC_NO  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND CASE WHEN DBO.FN_GET_LAST_PROC(A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.PROC_CD) = 'Y' THEN '*' ELSE A.PROC_CD END = B.PROC_CD  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	 AND A.S_CHK = B.S_CHK  
  
  
	--공정일지   
	DELETE A  
	FROM PD_RESULT_PROC_SPEC_VALUE A (NOLOCK)  
	INNER JOIN @TB_DELETE_RESULT B  
	 ON A.DIV_CD = B.DIV_CD  
	 AND A.PLANT_CD = B.PLANT_CD  
	 AND A.ORDER_NO = B.ORDER_NO  
	 AND A.REVISION = B.REVISION  
	 AND A.ORDER_TYPE = B.ORDER_TYPE  
	 AND A.ORDER_FORM = B.ORDER_FORM  
	 AND A.ROUT_NO = B.ROUT_NO  
	 AND A.ROUT_VER = B.ROUT_VER  
	 AND A.WC_CD = B.WC_CD  
	 AND A.LINE_CD = B.LINE_CD  
	 AND A.PROC_CD = B.PROC_CD  
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	 AND A.S_CHK = B.S_CHK  
  
  
	--검사삭제  
	DELETE B  
	FROM @TB_DELETE_RESULT A  
	INNER JOIN QC_PQC_ORDER B (NOLOCK)  
	 ON A.DIV_CD = B.DIV_CD   
	 AND A.PLANT_CD = B.PLANT_CD   
	 AND A.PROC_NO = B.PROC_NO   
	 AND A.ORDER_NO = B.ORDER_NO   
	 AND A.REVISION = B.REVISION   
	 AND A.ORDER_TYPE = B.ORDER_TYPE   
	 AND A.ORDER_FORM = B.ORDER_FORM   
	 AND A.ROUT_NO = B.ROUT_NO   
	 AND A.ROUT_VER = B.ROUT_VER   
	 AND A.WC_CD = B.WC_CD   
	 AND A.LINE_CD = B.LINE_CD   
	 AND A.PROC_CD = B.PROC_CD   
	 AND A.RESULT_SEQ = B.RESULT_SEQ  
	 AND A.S_CHK = B.S_CHK  
	-------데이터 삭제 끝  
  
	SET @MSG_CD = '0011'    -- 정상처리되었습니다.   
	SET @MSG_DETAIL = ''   
	RETURN 0   
END