--DELETE FROM FLEXAPI_NEW.DBO.IFM705_MASTER_TMP WHERE InboundId_ApiAutoCreate = 22

SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER_TMP_JWR WHERE InboundId_ApiAutoCreate = 31

SELECT *FROM PD_MDM_BASE_CODE where mcase = 'Bare 포장 종료'

UPDATE PD_MDM_BASE_CODE SET CODE = 'WEI_PV'
WHERE MCASE = 'Bare RHK 투입' AND SEQ = '2'

SELECT *FROM PD_MDM_WORK_SEND

SELECT *FROM BA_EQP WHERE MN_S <> ''

/*
UPDATE A SET A.MDM_TAG = 'LFG01A-01B-RCV-0401$G1_TRACKING.MASTER.G1B-DATA@.RHK-G101.RO-START-WEI-PV' FROM POP_EQP_ENO A WITH (NOLOCK) 
WHERE A.EQP_CD = 'LFG01A-01B-RCV-0401'
  AND A.PROC_SPEC_CD = 'E001'
*/
BEGIN TRAN 

SELECT *FROM PD_ORDER_PROC_SPEC A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250827002' AND A.EQP_CD = 'LFG01A-01B-RM-0501'

SELECT *FROM PD_MDM_WORK_SEND
/*
BEGIN TRAN 
SELECT *FROM PD_ORDER_WORK_SEND 

SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER_TMP
SELECT *FROM FLEXAPI_NEW.DBO.IFM705_MASTER_TMP_JWR 

BEGIN TRAN 
INSERT INTO FLEXAPI_NEW.DBO.IFM705_MASTER_TMP_JWR
SELECT '31', 'Recieved',null,'Bare 리본믹서 종료',null,null,null,null,null,'13G01B','SE',NULL,'LFG01A-01B-RM-0501',NULL,GETDATE(), GETDATE(), NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01B-RM-0501$G1_TRACKING.MASTER.G1B-DATA@.RM-G101.MIX-END-WEI-PV',5,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

ROLLBACK 

SELECT '29', 'Recieved',null,'Bare 리본믹서 시작',null,null,NULL,null,null,'13G01B','SE',NULL,'LFG01A-01B-RM-0501',NULL,GETDATE(), GETDATE(), NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01B-RCV-0401$G1_TRACKING.MASTER.G1B-DATA@.RHK-G101.RO-START-WEI-PV',5.5,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

ROLLB
INSERT INTO FLEXAPI_NEW.DBO.IFM705_MASTER_TMP_JWR
SELECT '30', 'Recieved',null,'Bare 리본믹서 종료',null,null,NULL,null,null,'13G01B','SE',NULL,'LFG01A-01B-RM-0501',NULL,GETDATE(), NULL, NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01B-RCV-0401$G1_TRACKING.MASTER.G1B-DATA@.RHK-G101.RO-START-WEI-PV',5.5,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

BEGIN TRAN 

INSERT INTO FLEXAPI_NEW.DBO.IFM705_MASTER_TMP 
SELECT '18', 'Recieved',null,'PreBare RK 배출 종료',null,null,null,null,null,'13G01A','RK',NULL,'LFG01A-01B-TK-0501',NULL,GETDATE(), GETDATE(), NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01B-TK-0501$G1_TRACKING.MASTER.G1B-DATA@.TK-G111.WEI-END-WEI-PV',165,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

SELECT '29', 'Recieved',null,'Bare 리본믹서 시작',null,null,NULL,null,null,'13G01B','SE',NULL,'LFG01A-01B-RM-0501',NULL,GETDATE(), GETDATE(), NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01B-RCV-0401$G1_TRACKING.MASTER.G1B-DATA@.RHK-G101.RO-START-WEI-PV',5.5,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

ROLLBACK 

SELECT '16', 'Recieved',null,'Pre-Bare RK 시작',null,null,null,null,null,'13G01A','RK',NULL,'LFG01A-01A-RK-0701',NULL,GETDATE(), NULL, NULL, NULL,
'G1_TRACKING.MASTER.G1A-DATA@.RK-G101.START-TIME1',0,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL

INSERT INTO FLEXAPI_NEW.DBO.IFM705_MASTER_TMP 
SELECT '15', 'Recieved',null,'Pre-Bare RK 종료',null,null,null,null,null,'13G01A','RK',NULL,'LFG01A-01A-RK-0701',NULL,GETDATE(), GETDATE(), NULL, NULL,
NULL,NULL,NULL,NULL, 'LFG01A-01A-RK-0701$G1_TRACKING.MASTER.G1A-DATA@.RK-G101.WEI-END-WEI-SV',165,
NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL


INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare 포장 시작', 1, 'START_DM','시작시간','SD','N','admin',GETDATE(),'admin',GETDATE()

--DELETE PD_MDM_BASE_CODE WHERE MCASE = 'Bare 포장 완료'

INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare 포장 완료', 1, 'NET_WEI','실중량','D','V','admin',GETDATE(),'admin',GETDATE()
INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare 포장 완료', 2, 'END_DM','종료시간','ED','N','admin',GETDATE(),'admin',GETDATE()


INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare RHK 배출 종료', 1, 'NET_WEI','실중량','D','V','admin',GETDATE(),'admin',GETDATE()

INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare RHK 배출 종료', 2, 'END_DM','종료시간','ED','N','admin',GETDATE(),'admin',GETDATE()

INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Pre-Bare RK 배출 종료', 2, 'END_DM','종료시간','ED','N','admin',GETDATE(),'admin',GETDATE()


INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Pre-Bare RK 종료', 1, 'END_DM','종료중량','ED','N','admin',GETDATE(),'admin',GETDATE()
INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Pre-Bare RK 종료', 2, 'NET_WEI','실중량','D','V','admin',GETDATE(),'admin',GETDATE()


SELECT *FROM PD_MDM_BASE_CODE 

select *from PD_MDM_ORDER_MASTER 
*/


COMMIT  
--UNION ALL 
--SELECT 'Pre-Bare 계량 완료', 2, 'NET_WEI','실중량','D','V','admin',GETDATE(),'admin',GETDATE()

/*
SELECT 
'Pre-Bare 원료투입 시작', 1, 'START_DM','시작시간','SD','N','admin',GETDATe(),'admin',GETDATE()
--UNION ALL 
--SELECT 
--'Pre-Bare 원료투입 시작', 2, 'START_WEI_TAG','시작중량 TAG','D','T','admin',GETDATe(),'admin',GETDATE()
UNION ALL 
SELECT 
'Pre-Bare 원료투입 시작', 2, 'START_WEI','시작중량','D','V','admin',GETDATe(),'admin',GETDATE()

UNION ALL 
SELECT 
'Pre-Bare 원료투입 종료', 1, 'END_DM','종료시간','ED','N','admin',GETDATe(),'admin',GETDATE()
--UNION ALL 
--SELECT 
--'Pre-Bare 원료투입 종료', 2, 'END_WEI_TAG','종료중량 TAG','D','T','admin',GETDATe(),'admin',GETDATE()
UNION ALL 
SELECT 
'Pre-Bare 원료투입 종료', 2, 'END_WEI','종료중량','D','V','admin',GETDATe(),'admin',GETDATE()

--UNION ALL 
--SELECT 
--'Pre-Bare 원료투입 종료', 4, 'NET_WEI_TAG','실중량 TAG','D','T','admin',GETDATe(),'admin',GETDATE()
UNION ALL 
SELECT 
'Pre-Bare 원료투입 종료', 3, 'NET_WEI','실중량','D','V','admin',GETDATe(),'admin',GETDATE()
*/
