
delete from PD_MDM_BASE_CODE
where mcase like 'bare 계량%'

INSERT INTO PD_MDM_BASE_CODE 
SELECT 'Bare 계량 ' + RIGHT(MCASE,2), SEQ, CODE, CODE_NM, FLAG, COL_CHK, INSERT_ID, INSERT_DT, UPDATE_ID, UPDATE_DT
FROM PD_MDM_BASE_CODE WHERE MCASE LIKE '%Pre-bare 계량%'

/*
SELECT *FROM BA_EQP A WHERE A.EQP_CD IN (
'LFG01A-01C-RK-0701'
,'LFG01A-01C-RM-0501'
,'LFG01A-01C-RM-0502'
) AND A.PROC_CD = 'RK'

UPDATE A SET A.MN_S = 'E', A.MN_FLAG = 'Y' FROM BA_EQP A WHERE A.EQP_CD IN (

'LFG01A-01C-RM-0501'
,'LFG01A-01C-RM-0502'
) AND A.PROC_CD = 'RK'

--SP_HELP PD_ORDER_PROC_SPEC 
BEGIN TRAN 
INSERT INTO PD_ORDER_PROC_SPEC 
SELECT 
 DIV_CD
,PLANT_CD
,ORDER_NO
,REVISION
,ORDER_TYPE
,ORDER_FORM
,ROUT_NO
,ROUT_VER
,WC_CD
,LINE_CD
,PROC_CD
,26
,SPEC_VERSION
,BASE_ITEM_CD
,STEP
,GROUP_SPEC_CD
,PROC_SPEC_CD
,'LFG01A-01C-RM-0502'
,RECYCLE_NO
,BASIC_UNIT
,SPEC_VALUE_TYPE
,USEM_ITEM_GROUP
,PROC_SPEC_U
,PROC_SPEC_L
,PROC_SPEC_VALUE
,PROC_SPEC_SETTING
,PROC_EQP_U
,PROC_EQP_L
,PROC_SETTING_VALUE
,PROC_DIGIT
,PROC_WARNING_U
,PROC_WARNING_L
,WARNING_TYPE
,PLC_FLAG
,CHK_FLAG
,REQ_FLAG
,REV_FLAG
,BYPASS_FLAG
,SET_FLAG
,AUTO_PLC_FLAG
,STOCK_ADD
,INQ_TYPE
,REMARK
,USE_YN
,CFM_FLG
,INSERT_ID
,INSERT_DT
,UPDATE_ID
,UPDATE_DT
,FMEA_CP_SEQ
FROM PD_ORDER_PROC_SPEC  A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250929001' AND A.PROC_CD = 'RK' AND A.PROC_SPEC_CD = 'E001' AND A.EQP_CD = 'LFG01A-01C-RK-0701'
ROLLBACK NE-K12S
SELECT *FROM PD_ORDER_PROC_SPEC  A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250929001' AND A.PROC_CD = 'RK' AND A.PROC_SPEC_CD = 'E001'
*/

UPDATE A SET A.USEM_ITEM_GROUP = 'NE-K12S' FROM PD_ORDER_PROC_SPEC  A WITH (NOLOCK) 
WHERE A.ORDER_NO = 'PD250929001' AND A.PROC_CD = 'SE' AND A.PROC_SPEC_CD = 'A016'
