--INSERT INTO PD_ORDER_PROC_SPEC
SELECT TOP 1
DIV_CD
,PLANT_CD
,ORDER_NO
,REVISION
,ORDER_TYPE
,ORDER_FORM
,ROUT_NO
,ROUT_VER
,WC_CD
,LINE_CD
,PROC_CD
,103
,SPEC_VERSION
,BASE_ITEM_CD
,STEP
,GROUP_SPEC_CD
,'E001'
,'LFG01A-01B-RCV-0402'
,RECYCLE_NO
,BASIC_UNIT
,SPEC_VALUE_TYPE
,USEM_ITEM_GROUP
,PROC_SPEC_U
,PROC_SPEC_L
,PROC_SPEC_VALUE
,PROC_SPEC_SETTING
,PROC_EQP_U
,PROC_EQP_L
,PROC_SETTING_VALUE
,PROC_DIGIT
,PROC_WARNING_U
,PROC_WARNING_L
,WARNING_TYPE
,PLC_FLAG
,CHK_FLAG
,REQ_FLAG
,REV_FLAG
,BYPASS_FLAG
,SET_FLAG
,AUTO_PLC_FLAG
,STOCK_ADD
,INQ_TYPE
,REMARK
,USE_YN
,CFM_FLG
,INSERT_ID
,INSERT_DT
,UPDATE_ID
,UPDATE_DT
,FMEA_CP_SEQ
FROM PD_ORDER_PROC_SPEC WHERE ORDER_NO = 'PD250827001' AND PROC_CD = 'RK' AND PROC_SPEC_CD = 'E001'


--UPDATE A SET A.USEM_ITEM_GROUP = 'NE-K12SB' FROM PD_ORDER_PROC_SPEC A WHERE ORDER_NO = 'PD250827002' AND PROC_CD = 'RH' AND PROC_SPEC_CD = 'E001'
--ORDER BY SEQ 