
Coating 계량 시작
Coating 계량 시작
Coating 계량 종료
Coating 계량 종료


/*
--SELECT A.PROC_SPEC_CD, B.SUB_NM, A.*
UPDATE A SET A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01A-TK-0901' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
  AND A.PROC_SPEC_CD = 'A050' 
--  AND A.PROC_SPEC_CD = 'B000'

UPDATE A SET A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-WEI-PV'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01A-TK-0901' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
 -- AND A.PROC_SPEC_CD = 'A050' 
  AND A.PROC_SPEC_CD = 'B000'

  */
  /*
--  SELECT A.PROC_SPEC_CD, B.SUB_NM, A.*
UPDATE A SET A.MDM_TAG = 'LFG01A-01B-TK-0503$G1_TRACKING.MASTER.G1B-DATA@.TK-G109.START-BF-WEI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0503' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
  AND A.PROC_SPEC_CD = 'A023'

  UPDATE A SET A.MDM_TAG = 'LFG01A-01B-TK-0503$G1_TRACKING.MASTER.G1B-DATA@.TK-G109.END-AF-WEI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0503' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
  AND A.PROC_SPEC_CD = 'A050'

  UPDATE A SET A.MDM_TAG = 'LFG01A-01B-TK-0503$G1_TRACKING.MASTER.G1B-DATA@.TK-G109.END-WEI-PV'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0503' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
  AND A.PROC_SPEC_CD = 'B000'
  */
/*
--    SELECT A.PROC_SPEC_CD, B.SUB_NM, A.*
UPDATE A SET A.MDM_TAG = 'LFG01A-01B-PK-0401$G1_TRACKING.MASTER.G1B-DATA@.FP-G101.PACK-END-WEI-PV'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-PK-0401' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'
  AND A.PROC_SPEC_CD = 'L009'


  SELECT A.* FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
  WHERE A.AUTO_NO = '252720002'

  UPDATE A SET A.EDATE = NULL FROM PD_MDM_RESULT_MASTER A 
  WHERE A.AUTO_NO = '252720002'
  UPDATE A SET A.END_DT = NULL FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
  WHERE A.AUTO_NO = '252720002' AND A.VALUE_STEP = 'ED'

*/

SELECT *FROM PD_MDM_BASE_CODE 

select TOP 50 *from FlexAPI_NEW.DBO.IFM705_MASTER A where a.InboundId_ApiAutoCreate >=1736
ORDER BY A.InboundId_ApiAutoCreate asc  

SELECT A.PROC_SPEC_CD, B.SUB_NM,A.MDM_TAG, A.*
--UPDATE A SET A.MDM_TAG = 'LFG01A-01B-PK-0401$G1_TRACKING.MASTER.G1B-DATA@.FP-G101.PACK-END-WEI-PV'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0401' --AND A.PROC_CD = 'SE' --AND A.MDM_TAG = 'LFG01A-01A-TK-0901$G1_TRACKING.MASTER.G1A-DATA@.TK-G105.END-AF-WEI'

--SELECT A.PROC_SPEC_CD, B.SUB_NM, A.*
UPDATE A SET A.MDM_TAG = 'LFG01A-01B-TK-0501$G1_TRACKING.MASTER.G1B-DATA@.TK-G111.WEI-END-AF-WEI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0501' AND A.PROC_SPEC_CD = 'C002'

UPDATE A SET A.MDM_TAG = 'LFG01A-01B-TK-0501$G1_TRACKING.MASTER.G1B-DATA@.TK-G111.WEI-START-BF-WEI'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01B-TK-0501' AND A.PROC_SPEC_CD = 'C001'

UPDATE A SET A.MDM_TAG = 'LFG01A-01C-LIW-0802$G1_TRACKING.MASTER.G1C-DATA@.TK-GC104.WEI-END-WEI-PV'
FROM POP_EQP_ENO A WITH (NOLOCK) 
INNER JOIN BA_SUB_CD B WITH (NOLOCK) ON A.PROC_SPEC_CD = B.SUB_CD AND B.MAIN_CD = 'P2001'
WHERE A.EQP_CD = 'LFG01A-01C-LIW-0802' AND A.PROC_SPEC_CD = 'C003'


