DECLARE @LINE_CD NVARCHAR(10) = '13G01D' 
       ,@DT NVARCHAR(10) = '2026-01-23'


-- 포장LOT, 투입LOT 

SELECT A.ORDER_NO, A.REVISION, A.PROC_CD, A.RESULT_SEQ, A.LOT_NO, B.BE_ORDER_NO, B.BE_REVISION, B.BE_PROC_CD, B.BE_RESULT_SEQ, B.LOT_NO, B.USEM_QTY
	FROM PD_RESULT A WITH (NOLOCK) 	
	INNER JOIN PD_USEM B WITH (NOLOCK) ON
	A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
	AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER 
	AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
WHERE A.LINE_CD = @LINE_CD AND A.SIL_DT = @DT AND A.PROC_CD ='DR'
AND A.LOT_NO = 'G2601-NLC-ASH-WU-01D-153'
;

SELECT A.ORDER_NO, A.REVISION, A.PROC_CD, A.RESULT_SEQ, A.LOT_NO, B.BE_ORDER_NO, B.BE_REVISION, B.BE_PROC_CD, B.BE_RESULT_SEQ, B.LOT_NO, B.USEM_QTY
	FROM PD_RESULT A WITH (NOLOCK) 	
	INNER JOIN PD_USEM B WITH (NOLOCK) ON
	A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
	AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER 
	AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
WHERE A.LINE_CD = @LINE_CD AND A.ORDER_NO = 'PD251224012' AND A.REVISION = '2' AND A.PROC_CD = 'FP' AND A.RESULT_SEQ = '154' 
AND A.LOT_NO = 'G2601-NLC-ASH-WU-01D-153'
;

SELECT A.ORDER_NO, A.REVISION, A.PROC_CD, A.RESULT_SEQ, A.LOT_NO, B.BE_ORDER_NO, B.BE_REVISION, B.BE_PROC_CD, B.BE_RESULT_SEQ, B.LOT_NO, B.REQ_NO, B.USEM_QTY
	FROM PD_RESULT A WITH (NOLOCK) 	
	INNER JOIN PD_USEM B WITH (NOLOCK) ON
	A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
	AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER 
	AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
WHERE A.LINE_CD = @LINE_CD AND A.ORDER_NO = 'PD251224012' AND A.REVISION = '2' AND A.PROC_CD = 'RI' AND A.RESULT_SEQ IN ('153','154')

;

WITH BASE AS
(
    /* ===============================
       DR → FP → RI → 원료 (세로)
       =============================== */
    SELECT
        DR.LOT_NO AS DR_LOT,
		DR.GOOD_QTY AS DR_QTY,
        FP.LOT_NO AS FP_LOT,
		FP.GOOD_QTY AS FP_QTY,
        RI.LOT_NO AS RI_LOT,
		RI.GOOD_QTY AS RI_QTY,

        RM.LOT_NO     AS RI_INPUT_LOT,
        RM.USEM_QTY   AS RI_INPUT_QTY,
        RM.REQ_NO     AS RI_REQ_NO     -- ⭐ 추가
    FROM PD_RESULT DR WITH (NOLOCK)

    /* DR → FP */
    INNER JOIN PD_USEM U1 WITH (NOLOCK)
        ON DR.DIV_CD      = U1.DIV_CD
       AND DR.PLANT_CD    = U1.PLANT_CD
       AND DR.ORDER_NO    = U1.ORDER_NO
       AND DR.REVISION    = U1.REVISION
       AND DR.ORDER_TYPE  = U1.ORDER_TYPE
       AND DR.ORDER_FORM  = U1.ORDER_FORM
       AND DR.ROUT_NO     = U1.ROUT_NO
       AND DR.ROUT_VER    = U1.ROUT_VER
       AND DR.WC_CD       = U1.WC_CD
       AND DR.LINE_CD     = U1.LINE_CD
       AND DR.PROC_CD     = U1.PROC_CD
       AND DR.RESULT_SEQ  = U1.RESULT_SEQ
       AND U1.BE_PROC_CD  = 'FP'

    INNER JOIN PD_RESULT FP WITH (NOLOCK)
        ON FP.DIV_CD      = U1.DIV_CD
       AND FP.PLANT_CD    = U1.PLANT_CD
       AND FP.ORDER_NO    = U1.BE_ORDER_NO
       AND FP.REVISION    = U1.BE_REVISION
       AND FP.PROC_CD     = 'FP'
       AND FP.RESULT_SEQ  = U1.BE_RESULT_SEQ

    /* FP → RI */
    INNER JOIN PD_USEM U2 WITH (NOLOCK)
        ON FP.DIV_CD      = U2.DIV_CD
       AND FP.PLANT_CD    = U2.PLANT_CD
       AND FP.ORDER_NO    = U2.ORDER_NO
       AND FP.REVISION    = U2.REVISION
       AND FP.ORDER_TYPE  = U2.ORDER_TYPE
       AND FP.ORDER_FORM  = U2.ORDER_FORM
       AND FP.ROUT_NO     = U2.ROUT_NO
       AND FP.ROUT_VER    = U2.ROUT_VER
       AND FP.WC_CD       = U2.WC_CD
       AND FP.LINE_CD     = U2.LINE_CD
       AND FP.PROC_CD     = U2.PROC_CD
       AND FP.RESULT_SEQ  = U2.RESULT_SEQ
       AND U2.BE_PROC_CD  = 'RI'

    INNER JOIN PD_RESULT RI WITH (NOLOCK)
        ON RI.DIV_CD      = U2.DIV_CD
       AND RI.PLANT_CD    = U2.PLANT_CD
       AND RI.ORDER_NO    = U2.BE_ORDER_NO
       AND RI.REVISION    = U2.BE_REVISION
       AND RI.PROC_CD     = 'RI'
       AND RI.RESULT_SEQ  = U2.BE_RESULT_SEQ

    /* RI → 원료 */
    INNER JOIN PD_USEM RM WITH (NOLOCK)
        ON RI.DIV_CD      = RM.DIV_CD
       AND RI.PLANT_CD    = RM.PLANT_CD
       AND RI.ORDER_NO    = RM.ORDER_NO
       AND RI.REVISION    = RM.REVISION
       AND RI.ORDER_TYPE  = RM.ORDER_TYPE
       AND RI.ORDER_FORM  = RM.ORDER_FORM
       AND RI.ROUT_NO     = RM.ROUT_NO
       AND RI.ROUT_VER    = RM.ROUT_VER
       AND RI.WC_CD       = RM.WC_CD
       AND RI.LINE_CD     = RM.LINE_CD
       AND RI.PROC_CD     = RM.PROC_CD
       AND RI.RESULT_SEQ  = RM.RESULT_SEQ

    WHERE DR.LINE_CD = @LINE_CD
      AND DR.SIL_DT  = @DT
      AND DR.PROC_CD = 'DR'
),
RN_BASE AS
(
    /* ===============================
       ROW 그대로 번호 부여
       =============================== */
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY DR_LOT, RI_LOT
            ORDER BY (SELECT 1)
        ) AS RN
    FROM BASE
)
SELECT
    DR_LOT,
	DR_QTY,
    FP_LOT,
	FP_QTY,
    RI_LOT,
	RI_QTY,

    MAX(CASE WHEN RN = 1 THEN RI_INPUT_LOT END) AS RI_INPUT_LOT_1,
    MAX(CASE WHEN RN = 1 THEN RI_INPUT_QTY END) AS RI_INPUT_QTY_1,
    MAX(CASE WHEN RN = 1 THEN RI_REQ_NO    END) AS RI_REQ_NO_1,

    MAX(CASE WHEN RN = 2 THEN RI_INPUT_LOT END) AS RI_INPUT_LOT_2,
    MAX(CASE WHEN RN = 2 THEN RI_INPUT_QTY END) AS RI_INPUT_QTY_2,
    MAX(CASE WHEN RN = 2 THEN RI_REQ_NO    END) AS RI_REQ_NO_2,

    MAX(CASE WHEN RN = 3 THEN RI_INPUT_LOT END) AS RI_INPUT_LOT_3,
    MAX(CASE WHEN RN = 3 THEN RI_INPUT_QTY END) AS RI_INPUT_QTY_3,
    MAX(CASE WHEN RN = 3 THEN RI_REQ_NO    END) AS RI_REQ_NO_3,

    MAX(CASE WHEN RN = 4 THEN RI_INPUT_LOT END) AS RI_INPUT_LOT_4,
    MAX(CASE WHEN RN = 4 THEN RI_INPUT_QTY END) AS RI_INPUT_QTY_4,
    MAX(CASE WHEN RN = 4 THEN RI_REQ_NO    END) AS RI_REQ_NO_4
FROM RN_BASE
WHERE DR_LOT= 'G2601-NLC-ASH-WU-01D-153'

GROUP BY
    DR_LOT, DR_QTY, FP_LOT, FP_QTY, RI_LOT, RI_QTY 
ORDER BY
    DR_LOT;

	
SELECT
    DR.LOT_NO        AS DR_LOT,
    FP.LOT_NO        AS FP_LOT,
    RI.LOT_NO        AS RI_LOT,
    RM.LOT_NO        AS RI_INPUT_LOT,
    RM.USEM_QTY      AS RI_INPUT_QTY
FROM PD_RESULT DR WITH (NOLOCK)

/* 1️⃣ DR → FP */
INNER JOIN PD_USEM U1 WITH (NOLOCK)
    ON DR.DIV_CD      = U1.DIV_CD
   AND DR.PLANT_CD    = U1.PLANT_CD
   AND DR.ORDER_NO    = U1.ORDER_NO
   AND DR.REVISION    = U1.REVISION
   AND DR.ORDER_TYPE  = U1.ORDER_TYPE
   AND DR.ORDER_FORM  = U1.ORDER_FORM
   AND DR.ROUT_NO     = U1.ROUT_NO
   AND DR.ROUT_VER    = U1.ROUT_VER
   AND DR.WC_CD       = U1.WC_CD
   AND DR.LINE_CD     = U1.LINE_CD
   AND DR.PROC_CD     = U1.PROC_CD
   AND DR.RESULT_SEQ  = U1.RESULT_SEQ
   AND U1.BE_PROC_CD  = 'FP'

INNER JOIN PD_RESULT FP WITH (NOLOCK)
    ON FP.ORDER_NO    = U1.BE_ORDER_NO
   AND FP.REVISION    = U1.BE_REVISION
   AND FP.PROC_CD     = 'FP'
   AND FP.RESULT_SEQ  = U1.BE_RESULT_SEQ

/* 2️⃣ FP → RI */
INNER JOIN PD_USEM U2 WITH (NOLOCK)
    ON FP.DIV_CD      = U2.DIV_CD
   AND FP.PLANT_CD    = U2.PLANT_CD
   AND FP.ORDER_NO    = U2.ORDER_NO
   AND FP.REVISION    = U2.REVISION
   AND FP.ORDER_TYPE  = U2.ORDER_TYPE
   AND FP.ORDER_FORM  = U2.ORDER_FORM
   AND FP.ROUT_NO     = U2.ROUT_NO
   AND FP.ROUT_VER    = U2.ROUT_VER
   AND FP.WC_CD       = U2.WC_CD
   AND FP.LINE_CD     = U2.LINE_CD
   AND FP.PROC_CD     = U2.PROC_CD
   AND FP.RESULT_SEQ  = U2.RESULT_SEQ
   AND U2.BE_PROC_CD  = 'RI'

INNER JOIN PD_RESULT RI WITH (NOLOCK)
    ON RI.ORDER_NO    = U2.BE_ORDER_NO
   AND RI.REVISION    = U2.BE_REVISION
   AND RI.PROC_CD     = 'RI'
   AND RI.RESULT_SEQ  = U2.BE_RESULT_SEQ

/* 3️⃣ RI → 원료 (여기가 핵심) */
INNER JOIN PD_USEM RM WITH (NOLOCK)
    ON RI.DIV_CD      = RM.DIV_CD
   AND RI.PLANT_CD    = RM.PLANT_CD
   AND RI.ORDER_NO    = RM.ORDER_NO
   AND RI.REVISION    = RM.REVISION
   AND RI.ORDER_TYPE  = RM.ORDER_TYPE
   AND RI.ORDER_FORM  = RM.ORDER_FORM
   AND RI.ROUT_NO     = RM.ROUT_NO
   AND RI.ROUT_VER    = RM.ROUT_VER
   AND RI.WC_CD       = RM.WC_CD
   AND RI.LINE_CD     = RM.LINE_CD
   AND RI.PROC_CD     = RM.PROC_CD
   AND RI.RESULT_SEQ  = RM.RESULT_SEQ

WHERE
    DR.LINE_CD = @LINE_CD
    AND DR.SIL_DT  = @DT
    AND DR.PROC_CD = 'DR'
    --AND DR.LOT_NO  = 'G2601-NLC-ASH-WU-01D-153';

--SELECT *FROM PD_INTEG_MANAGEMENT