
SELECT B.EQP_CD, C.EQP_NM, B.*FROM PD_RESULT A WITH (NOLOCK) 
INNER JOIN PD_RESULT_PROC_SPEC_VALUE B WITH (NOLOCK) ON A.ORDER_NO = B.ORDEr_NO AND A.REVISION = B.REVISION 
AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
INNER JOIN BA_EQP C WITH (NOLOCK) ON B.EQP_CD = C.EQP_CD 
WHERE A.PROC_CD = 'MX' AND A.EDATE IS NULL 

--DELETE FROM PD_USEM WHERE INSERT_DT >= '2025-09-04'
SELECT *FROM PD_MDM_RESULT_PROC_SPEC

UPDATE A SET A.END_DT = NULL
FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
WHERE A.PROC_CD = 'MX' AND A.VALUE_STEP = 'D' AND TAG_ID = 'L1PBMX.L1PBMX.L1PBMXW216'
--'L1PBMX.L1PBMX.L1PBMXW226'

INSERT INTO PD_MDM_RESULT_PROC_SPEC 
SELECT 'PD250113002', '13GA', '13G01A','MX','LFG-LW-08-02','L1PBMX.L1PBMX.L1PBMXW226',1,'D','700','1','',GETDATE(),NULL 

SELECT *FROM POP_EQP_ENO WHERE EQP_CD = 'LFG-LW-08-02'


EXEC USP_POP_004_RESULT_QUERY1 
 @DIV_CD = '01' 
,@PLANT_CD = '1130' 
,@PROC_NO = 'OPL2501130005' 
,@ORDER_NO = 'PD250113002' 
,@REVISION = '1' 
,@ORDER_TYPE = 'PP03' 
,@ORDER_FORM = '10' 
,@ROUT_NO = 'A01' 
,@ROUT_VER = '1' 
,@WC_CD = '13GA' 
,@LINE_CD = '13G01A' 
,@PROC_CD = 'MX' 
,@S_CHK = 'N' 
,@RESULT_SEQ = '635' 
,@EQP_CD = '%' 
,@CYCLE_SEQ = 1  