ALTER PROC USP_POP_004_RESULT_ROW_STATUS 
(
--    DECLARE 
        @DIV_CD      NVARCHAR(10)  = '01' 
       ,@PLANT_CD    NVARCHAR(10)  = '1130' 
) 
AS  
 /*

EXEC USP_POP_004_RESULT_ROW_STATUS '01','1130'
 */
DECLARE @ROW_TABLE TABLE ( 
     ID          INT IDENTITY(1,1) 
    ,K           NVARCHAR(100) -- DIV_CD, PLANT_CD, WC_CD, LINE_CD, PROC, EQP 까지 갑시다.  
    ,GBN         NVARCHAR(10)
    ,STATUS      NVARCHAR(100) 
    
    ,ORDER_NO    NVARCHAR(100) 
    ,ADDR        NVARCHAR(100)
    ,VALUE       NUMERIC(18,4) 
    ,SETUP       NVARCHAR(100)
    
    --,UPDATEAT    DATETIME  
) 
 
-- 현재 공정 마스터를 가지고 온다. 
INSERT INTO @ROW_TABLE  
SELECT A.DIV_CD + '/' + A.PLANT_CD + '/' + A.WC_CD + '/' + B.LINE_CD + '/' + A.PROC_CD + '/' + ISNULL(C.EQP_CD,''), 
'ST', 
CASE WHEN ISNULL(D.ORDER_NO,'') <> '' AND D.DEL_FLG = 'Y' THEN 'S' 
     WHEN ISNULL(D.ORDER_NO,'') <> '' AND D.DEL_FLG = 'N' THEN 'Y' 
     WHEN ISNULL(D.ORDER_NO,'') = '' THEN 'N'
END ,
ISNULL(D.ORDER_NO,''), '', 0, ''
FROM BA_PROC_MAIN A WITH (NOLOCK)  
INNER JOIN BA_LINE B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.WC_CD =B.WC_CD  
LEFT JOIN BA_EQP C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD AND B.LINE_CD = C.LINE_CD  AND A.PROC_CD = C.PROC_CD AND C.MN_FLAG = 'Y'  
LEFT JOIN PD_RESULT D WITH (NOLOCK) ON  
A.DIV_CD = D.DIV_CD AND A.PLANT_CD = D.PLANT_CD AND A.WC_CD = D.WC_CD AND B.LINE_CD = D.LINE_CD AND A.PROC_CD = D.PROC_CD AND C.EQP_CD = D.EQP_CD 
AND D.EDATE IS NULL 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD  
ORDER BY A.WC_CD, B.LINE_CD, A.PROC_SEQ, C.EQP_CD 
/*
INSERT INTO @ROW_TABLE  
SELECT DISTINCT A.DIV_CD + '/' + A.PLANT_CD + '/' + A.WC_CD + '/' + B.LINE_CD + '/' + A.PROC_CD + '/' + ISNULL(C.EQP_CD,''), 'VAL'

,H.VALUE_STEP
, D.ORDER_NO
, 
CASE WHEN CHARINDEX('-',G.TEMP_CD4) = 0 THEN E.PROC_SPEC_CD ELSE 

    CASE WHEN H.VALUE_STEP = 'S' THEN 
        REPLACE(REPLACE(REPLACE(SUBSTRING(G.TEMP_CD4,0,CHARINDEX('-',G.TEMP_CD4)),' ' ,''),'[',''),']','')
         WHEN H.VALUE_STEP = 'E' THEN 
        REPLACE(REPLACE(REPLACE(SUBSTRING(G.TEMP_CD4,CHARINDEX('-',G.TEMP_CD4) + 1, LEN(G.TEMP_CD4)),' ',''),'[',''),']','')
    END 
END 
,H.VALUE
,F.OPC_AS + '.' + F.OPC_AS + '.' + F.POP_IP_ENO_AS

FROM BA_PROC_MAIN A WITH (NOLOCK)  
INNER JOIN BA_LINE B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.WC_CD =B.WC_CD  
INNER JOIN BA_EQP C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD AND B.LINE_CD = C.LINE_CD  AND A.PROC_CD = C.PROC_CD AND C.MN_FLAG = 'Y'  
INNER JOIN PD_RESULT D WITH (NOLOCK) ON  
A.DIV_CD = D.DIV_CD AND A.PLANT_CD = D.PLANT_CD AND A.WC_CD = D.WC_CD AND B.LINE_CD = D.LINE_CD AND A.PROC_CD = D.PROC_CD AND C.EQP_CD = D.EQP_CD 
AND D.EDATE IS NULL 
INNER JOIN PD_RESULT_PROC_SPEC_VALUE E WITH (NOLOCK) ON 
D.DIV_CD = E.DIV_CD AND D.PLANT_CD = E.PLANT_CD AND D.ORDER_NO = E.ORDER_NO AND D.REVISION = E.REVISION AND D.ORDER_TYPE = E.ORDER_TYPE AND 
D.ORDER_FORM = E.ORDER_FORM AND D.ROUT_NO = E.ROUT_NO AND D.ROUT_vER = E.ROUT_VER AND D.WC_CD = E.WC_CD AND D.LINE_CD = E.LINE_CD AND D.PROC_CD = E.PROC_CD AND D.RESULT_SEQ = 
E.RESULT_SEQ 
INNER JOIN POP_EQP_ENO F WITH (NOLOCK) ON E.DIV_CD = F.DIV_CD AND E.PLANT_CD = F.PLANT_CD AND E.PROC_CD = F.PROC_CD AND E.EQP_CD = F.EQP_CD AND E.PROC_SPEC_CD = F.PROC_SPEC_CD
INNER JOIN BA_SUB_CD G WITH (NOLOCK) ON E.PROC_SPEC_CD = G.SUB_CD AND G.MAIN_CD = 'P2001'
INNER JOIN PD_MDM_RESULT_PROC_SPEC H WITH (NOLOCK) ON E.ORDER_NO = H.ORDER_NO AND E.WC_CD = H.WC_CD AND E.LINE_CD = H.LINE_CD AND E.PROC_CD = H.PROC_CD 
AND E.EQP_CD = H.EQP_CD AND F.OPC_AS + '.' + F.OPC_AS + '.' + F.POP_IP_ENO_AS = H.TAG_ID AND H.END_DT IS NULL
WHERE A.DIV_CD = '01' AND A.PLANT_CD = '1130'
--ORDER BY A.WC_CD, B.LINE_CD, A.PROC_SEQ, C.EQP_CD 
*/
SELECT *FROM @ROW_TABLE 

