ALTER PROC USP_BASE_POP_MAIN_PROC 
( 
     @DIV_CD       NVARCHAR(10) 
    ,@PLANT_CD     NVARCHAr(15)  
    ,@WC_CD        NVARCHAR(15)  
    ,@LINE_CD      NVARCHAR(15)  
    ,@PROC_CD      NVARCHAR(10) = '%' 
    ,@CHK          NVARCHAR(10) = '' 
 
) 
AS  
/* 
 
EXEC USP_BASE_POP_MAIN_PROC  
 @DIV_CD = '01'  
,@PLANT_CD = '1130'  
,@WC_CD = '13GA'  
,@LINE_CD = '13G01A'  
 
*/ 
 
DECLARE @LAST_DATA TABLE  
( 
     CNT          INT IDENTITY(1,1)  
    ,PROC_CD      NVARCHAR(10)  
    ,PROC_NM      NVARCHAR(50)  
    ,EQP_CD       NVARCHAR(20)  
    ,EQP_NM       NVARCHAR(50) 
    ,PROC_SEQ     INT  
    ,DR_GBN       NVARCHAR(10) 
) 
 
INSERT INTO @LAST_DATA  
SELECT A.PROC_CD, B.PROC_NM, C.EQP_CD, C.EQP_NM, A.PROC_SEQ , CASE WHEN C.MN_S = 'Y' THEN A.DR_GBN ELSE 

CASE WHEN A.PROC_CD IN ('RK', 'RH') THEN 
'N' ELSE A.DR_GBN END 

END
    FROM BA_PROC_MAIN A WITH (NOLOCK)  
    INNER JOIN BA_PROC B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PROC_CD = B.PROC_CD  
    INNER JOIN BA_EQP C WITH (NOLOCK) ON A.DIV_CD = C.DIV_CD AND A.PLANT_CD = C.PLANT_CD AND A.WC_CD = C.WC_CD  
    AND A.PROC_CD = C.PROC_CD AND C.MN_FLAG = 'Y' 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD   
  AND A.WC_CD = @WC_CD AND C.LINE_CD = @LINE_CD 
  AND A.PROC_CD LIKE '%' + @PROC_CD + '%' 
ORDER BY A.PROC_SEQ  


SELECT A.PROC_CD, A.PROC_NM, MAX(A.PROC_SEQ) + ISNULL((SELECT COUNT(*) FROM @LAST_DATA WHERE DR_GBN = 'Y'),0) AS LAST_PROC_SEQ 
FROM @LAST_DATA A  
GROUP BY A.PROC_CD, A.PROC_NM  
ORDER BY LAST_PROC_SEQ 

 
SELECT A.CNT, A.PROC_CD, A.PROC_NM, A.EQP_CD, A.EQP_NM, A.PROC_SEQ, 'N' AS DR_GBN FROM @LAST_DATA A  
UNION ALL 
SELECT A.* FROM @LAST_DATA A WHERE A.DR_GBN = 'Y'




