ALTER PROC USP_POP_004_MATERIAL_LOT_QUERY(
--DECLARE
     @DIV_CD        NVARCHAR(10)   = '01'
    ,@PLANT_CD      NVARCHAR(10)   = '1130'
    ,@ORDER_NO      NVARCHAR(50)   = 'PD250113002'
    ,@REVISION      INT            = '1'
    ,@WC_CD         NVARCHAR(10)   = '13GA'
    ,@LINE_CD       NVARCHAR(10)   = '13G01A' 
    ,@PROC_CD       NVARCHAR(10)   = 'RI'
    ,@EQP_CD        NVARCHAR(50)   = 'LFG-MST-10-02'
    ,@RESULT_SEQ    INT = 0
)
AS 

IF EXISTS(SELECT *FROM PD_RESULT A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD 
AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.EQP_CD = @EQP_CD AND A.EDATE IS NULL)

BEGIN 
    SELECT B.USEM_SEQ, B.ITEM_CD, C.ITEM_NM, B.LOT_NO, B.BARCODE, B.USEM_QTY 
        FROM PD_RESULT A WITH (NOLOCK) 
        INNER JOIN PD_USEM B WITH (NOLOCK) ON A.DIV_CD = B.DIV_cD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION AND 
        A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND 
        A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
        INNER JOIN V_ITEM C WITH (NOLOCK) ON B.PLANT_CD = C.PLANT_CD AND B.ITEM_CD = C.ITEM_CD 
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD 
    AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD AND A.EQP_CD = @EQP_CD AND A.EDATE IS NULL

END 
ELSE 
BEGIN 
    SELECT B.USEM_SEQ, B.ITEM_CD, C.ITEM_NM, B.LOT_NO, B.BARCODE, B.USEM_QTY
        FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        INNER JOIN PD_USEM_MAT_TEMP B WITH (NOLOCK) ON 
        A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION AND 
        A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER AND
        A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.USEM_EQP = B.USEM_EQP AND A.RESULT_SEQ = B.RESULT_SEQ AND A.TEMP_SEQ = B.TEMP_SEQ 
        INNER JOIN V_ITEM C WITH (NOLOCK) ON A.PLANT_CD = C.PLANT_CD AND B.ITEM_CD = C.ITEM_CD 
    WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD 
    AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION 
    AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD 
    AND A.USEM_EQP = @EQP_CD 
    AND A.START_YN = 'N'
END     