ALTER PROC USP_POP_004_MATERIAL_MAT_DELETE(
--DECLARE 
     @DIV_CD            NVARCHAR(10) 
    ,@PLANT_CD          NVARCHAR(10) 
    ,@ORDER_NO          NVARCHAR(50) 
    ,@REVISION          INT 
    ,@WC_CD             NVARCHAR(10) 
    ,@LINE_CD           NVARCHAR(10) 
    ,@PROC_CD           NVARCHAR(10) 
    ,@EQP_CD            NVARCHAR(50)
    ,@USEM_SEQ          INT            = 0
    ,@USER_ID           NVARCHAR(15) 
    ,@MSG_CD            NVARCHAR(4)    OUTPUT 
    ,@MSG_DETAIL        NVARCHAR(MAX)  OUTPUT 

)
AS 

-- 작업 시작중인 데이터가 있으면? 튕겨 낸다.

IF EXISTS(SELECT *FROM PD_RESULT A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD 
  AND A.EQP_CD = @EQP_CD AND A.EDATE IS NULL 
)
BEGIN 
    SET @MSG_CD = '0060' 
    SET @MSG_DETAIL = '이미 가동중인 내역입니다. 삭제할수 없습니다.'

    RETURN 1
END 


BEGIN TRY
    IF EXISTS(
        SELECT B.*FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        INNER JOIN PD_USEM_MAT_TEMP B WITH (NOLOCK) 
        ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
        AND A.PROC_NO = B.PROC_NO AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.USEM_EQP = B.USEM_EQP
        AND A.RESULT_SEQ = B.RESULT_SEQ AND A.TEMP_SEQ = B.TEMP_SEQ 
        WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
        AND A.PROC_CD = @PROC_CD AND A.USEM_EQP = @EQP_CD AND B.USEM_SEQ = @USEM_SEQ 
        AND A.START_YN = 'N'
    )
    BEGIN 

        -- 배정이 있으면 배정부터 UPDATE 진행

        UPDATE C SET C.USE_QTY = 0, C.USE_FLG = 'Y'
        FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        INNER JOIN PD_USEM_MAT_TEMP B WITH (NOLOCK) 
        ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
        AND A.PROC_NO = B.PROC_NO AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.USEM_EQP = B.USEM_EQP
        AND A.RESULT_SEQ = B.RESULT_SEQ AND A.TEMP_SEQ = B.TEMP_SEQ 
        INNER JOIN MT_ITEM_OUT_BATCH C WITH (NOLOCK) ON B.DIV_CD = C.DIV_CD AND B.PLANT_CD = C.PLANT_CD AND B.REQ_NO = C.REQ_NO 
        WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
        AND A.PROC_CD = @PROC_CD AND A.USEM_EQP = @EQP_CD AND B.USEM_SEQ = @USEM_SEQ 
        AND A.START_YN = 'N'

        DELETE B FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        INNER JOIN PD_USEM_MAT_TEMP B WITH (NOLOCK) 
        ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
        AND A.PROC_NO = B.PROC_NO AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.USEM_EQP = B.USEM_EQP
        AND A.RESULT_SEQ = B.RESULT_SEQ AND A.TEMP_SEQ = B.TEMP_SEQ 
        WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
        AND A.PROC_CD = @PROC_CD AND A.USEM_EQP = @EQP_CD AND B.USEM_SEQ = @USEM_SEQ 
        AND A.START_YN = 'N'

    END 

    -- 해당 내역이 아무것도 없으면? 

    IF NOT EXISTS(
        SELECT B.* FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        INNER JOIN PD_USEM_MAT_TEMP B WITH (NOLOCK) 
        ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
        AND A.PROC_NO = B.PROC_NO AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM AND A.ROUT_NO = B.ROUT_NO
        AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.USEM_EQP = B.USEM_EQP
        AND A.RESULT_SEQ = B.RESULT_SEQ AND A.TEMP_SEQ = B.TEMP_SEQ 
        WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
        AND A.PROC_CD = @PROC_CD AND A.USEM_EQP = @EQP_CD AND B.USEM_SEQ = @USEM_SEQ 
        AND A.START_YN = 'N'
    )
    BEGIN 
        -- 마스터도 삭제 해준다.
        DELETE A FROM PD_USEM_MAT_TEMP_MASTER A WITH (NOLOCK) 
        WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.ORDER_NO = @ORDER_NO AND A.REVISION = @REVISION AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD 
        AND A.PROC_CD = @PROC_CD AND A.USEM_EQP = @EQP_CD 
        AND A.START_YN = 'N'
    END 
END TRY 
BEGIN CATCH 
    SET @MSG_CD = '9999'
    SET @MSG_DETAIL = ERROR_MESSAGE() 
    RETURN 1
END CATCH