ALTER PROC USP_POP_004_MATERIAL_INFO_QUERY(
--DECLARE
     @DIV_CD               NVARCHAR(10)   = '01'
    ,@PLANT_CD             NVARCHAR(10)   = '1130'
    ,@WC_CD                NVARCHAR(15)   = '13GA'
    ,@LINE_CD              NVARCHAR(15)   = '13G01A'
    ,@PROC_CD              NVARCHAR(10)   = 'RI'
    ,@EQP_CD               NVARCHAr(20)   = 'LFG-MST-10-02'
)
AS 

-- 코드에 따른 이름만 가지고 오면 된다. 
SELECT (
SELECT A.WC_NM
    FROM BA_WORK_CENTER A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD  
) AS WC_NM,
(SELECT A.LINE_NM
    FROM BA_LINE A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.LINE_CD = @LINE_CD 
) AS LINE_NM,
(SELECT A.PROC_NM
    FROM BA_PROC A WITH (NOLOCK) 
WHERE A.PROC_CD = @PROC_CD) AS PROC_NM,
(SELECT A.EQP_NM FROM BA_EQP A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.PROC_CD = @PROC_CD AND A.EQP_CD = @EQP_cD 
) AS EQP_NM


IF EXISTS(SELECT *FROM PD_RESULT A WITH (NOLOCK) 
WHERE A.DIV_CD = @DIV_CD AND A.PLANT_CD = @PLANT_CD AND A.WC_CD = @WC_CD AND A.LINE_CD = @LINE_CD AND A.PROC_CD = @PROC_CD 
  AND A.EQP_CD = @EQP_cD 
  AND A.EDATE IS NULL
)
BEGIN 
    SELECT 'Y' AS CHK
END 
ELSE 
BEGIN 
    SELECT 'N' AS CHK
END 