DECLARE @LOT_NO NVARCHAR(50) = 'M-HV04-2511-039'

--SELECT *FROM ST_ITEM_IN WHERE LOT_NO = @LOT_NO 
--ORDER BY IN_DATE ASC 

--SELECT *FROM SAP_Z02MESF_M010 WHERE ZVLOT = @LOT_NO 

SELECT *FROM ST_STOCK_NOW WHERE LOT_NO = @LOT_NO AND QTY > 0 AND LOCATION_NO = '*'

SELECT PLANT_CD,SL_CD, SUM(QTY) FROM ST_STOCK_NOW WHERE LOT_NO = @LOT_NO AND QTY > 0 
AND LOCATION_NO = '*' --and plant_cd = '1130'
GROUP BY PLANT_CD, SL_CD 
SELECT *FROM SAP_Z02MESF_M040 WHERE ZVLOT = @LOT_NO --and werks = '1130'

SELECT *FROM SAP_Z02MESF_M050 WHERE ZVLOT = @LOT_NO
ORDER BY ZMESIFNO DESC 

select *from ST_ITEM_IN WHERE LOT_NO = @LOT_NO AND PROC_CD = '*'
ORDER BY IN_DATE DESC, IN_SEQ DESC 

select *from ST_ITEM_OUT WHERE LOT_NO = @LOT_NO AND PROC_CD = '*'
ORDER BY OUT_DATE DESC, OUT_SEQ DESC 

SELECT *FROM SAP_Z02MESF_P030 WHERE ZLOTNO = @LOT_NO
ORDER BY ZMESIFNO DESC 

