/*

SELECT *FROM PD_MDM_RESULT_PROC_SPEC
SELECT *FROM PD_MDM_WORK_SEND 
SELECT *FROM PD_MDM_RESULT_MASTER
SELECT *FROM PD_MDM_BASE_CODE

SELECT *FROM FLEXMES_NEW.DBO.PD_MDM_RESULT_PROC_SPEC
SELECT *FROM FLEXMES_NEW.DBO.PD_MDM_WORK_SEND 
SELECT *FROM FLEXMES_NEW.DBO.PD_MDM_RESULT_MASTER
SELECT *FROM FLEXMES_NEW.DBO.PD_MDM_BASE_CODE



*/