-- 삭제 트리거

BEGIN TRAN 

-- MT_ITEM_OUT_BATCH 정리

UPDATE C SET C.USE_QTY = 0, C.USE_FLG = 'Y' 
FROM MT_ITEM_OUT_BATCH C 
WHERE C.ORDER_NO in ('PD251023001')


UPDATE C SET C.USE_QTY = 0, C.USE_FLG = 'Y' 
FROM PD_RESULT A WITH (NOLOCK) 
INNER JOIN PD_USEM B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD 
AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD 
AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ 
INNER JOIN MT_ITEM_OUT_BATCH C WITH (NOLOCK) ON B.REQ_NO = C.REQ_NO 
WHERE A.ORDER_NO in ('PD251023001')
-- PD_RESULT_PROC_SPEC_VALUE 삭제

DELETE A FROM PD_RESULT_PROC_SPEC_VALUE A
WHERE A.ORDER_NO in ('PD251023001')


-- PD_USEM 삭제 
DELETE A FROM PD_USEM A
WHERE A.ORDER_NO in ('PD251023001','')

-- PD_RESULT 삭제
DELETE A FROM PD_RESULT A WITH (NOLOCK) 
WHERE A.ORDER_NO in ('PD251023001')

DELETE A FROM PD_ITEM_IN A WITH (NOLOCK) 
WHERE A.ORDER_NO in ('PD251023001')
-- PD_USEM TEMP 삭제

DELETE PD_USEM_MAT_TEMP 
DELETE PD_USEM_MAT_TEMP_MASTER
DELETE PD_MDM_RESULT_MASTER
/*
UPDATE A SET A.END_DT = NULL 
FROM PD_MDM_RESULT_PROC_SPEC A WITH (NOLOCK) 
*/
DELETE PD_MDM_RESULT_PROC_SPEC
DELETE PD_MDM_WORK_SEND 

COMMIT  



--SELECT *FROM PD_MDM_RESULT_PROC_SPEC

