/*
기안번호 : PM250421005
기안구분 : 일반
제목 : G2B 혼합 투입된 Li2CO3 재공 Lot 변경 요청
일자 : 2025-04-25
작업자 : 임종원 이사
*/


BEGIN TRAN 
DECLARE @BACK_DATA TABLE 
(
     CNT           INT IDENTITY(1,1) 
    ,LOT_NO        NVARCHAR(50) 
    ,USEM_LOT      NVARCHAR(50)
    ,USEM_QTY      NUMERIC(18,3) 
    ,DIV_CD        NVARCHAR(10) 
    ,PLANT_CD      NVARCHAR(10) 
    ,ORDER_NO      NVARCHAR(50) 
    ,REVISION      INT 
    ,WC_CD         NVARCHAR(10) 
    ,LINE_CD       NVARCHAR(10) 
    ,PROC_CD       NVARCHAR(10) 
    ,RESULT_SEQ    INT
    ,USEM_SEQ      INT 
    ,BE_ORDER_NO   NVARCHAR(50)  
    ,BE_REVISION   INT 
    ,BE_PROC_CD    NVARCHAR(10)
    ,BE_RESULT_SEQ INT 

)

INSERT INTO @BACK_DATA

SELECT A.LOT_NO, B.LOT_NO, B.USEM_QTY,
A.DIV_CD, A.PLANT_CD, A.ORDER_NO, A.REVISION, A.WC_CD, A.LINE_CD, A.PROC_CD, A.RESULT_SEQ, B.USEM_SEQ, B.BE_ORDER_NO, B.BE_REVISION, B.BE_PROC_CD, B.BE_RESULT_SEQ

FROM PD_RESULT A WITH (NOLOCK) 
INNER JOIN PD_USEM B WITH (NOLOCK) ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD 
AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION AND A.ORDER_TYPE = B.ORDER_TYPE AND A.ORDER_FORM = B.ORDER_FORM 
AND A.ROUT_NO = B.ROUT_NO AND A.ROUT_VER = B.ROUT_VER AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD 
AND A.RESULT_SEQ = B.RESULT_SEQ AND B.LOT_NO = '1113015491'
WHERE A.LOT_NO BETWEEN 'G2504-CLC-NAD-BN-2001' AND 'G2504-CLC-NAD-BN-2005' AND A.PROC_CD = 'MX'
ORDER BY A.LOT_NO

-- 1. 원료 투입 내역을 1113015704 로 모두 변경한다. 실적 순번은 142 pd_usem 에 lot 변경, be_result_seq =142 로 변경 

UPDATE A 
 SET A.LOT_NO = '1113015704', A.MASTER_LOT = '1113015704', A.BE_RESULT_SEQ = '142'
    FROM PD_USEM A WITH (NOLOCK) 
    INNER JOIN @BACK_DATA B ON A.DIV_CD = B.DIV_CD AND A.PLANT_CD = B.PLANT_CD AND A.ORDER_NO = B.ORDER_NO AND A.REVISION = B.REVISION 
    AND A.WC_CD = B.WC_CD AND A.LINE_CD = B.LINE_CD AND A.PROC_CD = B.PROC_CD AND A.RESULT_SEQ = B.RESULT_SEQ AND A.USEM_SEQ = B.USEM_SEQ AND A.LOT_NO = B.USEM_LOT 

SELECT *FROM ST_STOCK_NOW A WITH (NOLOCK) 
WHERE A.LOT_NO = '1113015491' AND A.SL_CD = '3000' AND A.PROC_CD = 'RI' AND A.LOCATION_NO = '13G02B' 
-- 2. 투입 이력의 중량을 증가 시킨다. 142 ri 에 923.0 더 증가 13G02B


UPDATE A SET A.GOOD_QTY = A.GOOD_QTY + 923, A.RESULT_QTY = A.RESULT_QTY + 923
    FROM PD_RESULT A WITH (NOLOCK)
WHERE A.DIV_CD = '01' AND A.PLANT_CD = '1130' AND A.ORDER_NO = 'PD250113005' AND A.REVISION = '1' AND A.RESULT_SEQ = '142' AND A.PROC_CD = 'RI'

UPDATE A SET A.GOOD_QTY = A.GOOD_QTY + 923
    FROM PD_ITEM_IN A WITH (NOLOCK)
WHERE A.DIV_CD = '01' AND A.PLANT_CD = '1130' AND A.ORDER_NO = 'PD250113005' AND A.REVISION = '1' AND A.RESULT_SEQ = '142' AND A.PROC_CD = 'RI'

SELECT *FROM ST_STOCK_NOW A WITH (NOLOCK) 
WHERE A.LOT_NO = '1113015704' AND A.SL_CD = '3000' AND A.PROC_CD = 'RI' AND A.LOCATION_NO = '13G02B' 

-- 3. 기존 내역 141 재공을 조정 한다. 재공 실사 자료를 조정


DECLARE @OUT_DATE NVARCHAR(10) = '2025-04-23'
       ,@OUT_SEQ  INT 

SET @OUT_SEQ = ISNULL((SELECT MAX(OUT_SEQ) FROM ST_ITEM_OUT A WITH (NOLOCK) 
WHERE CONVERT(NVARCHAR(10), A.OUT_DATE,120) = @OUT_DATE 
),0) + 1

INSERT INTO ST_ITEM_OUT 
SELECT '01','1130',@OUT_DATE, @OUT_SEQ, 'RL10004','506','13GB','RI','1113015491','KG',923,'ST_ITEM_OUT','PD250113005','1','141',NULL,null, '3000',
'13G02B','*',NULL,'*','*',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'haesol_ljw',getdate(),NULL,NULL



SELECT *FROM ST_STOCK_NOW A WITH (NOLOCK) 
WHERE A.LOT_NO = '1113015491' AND A.SL_CD = '3000' AND A.PROC_CD = 'RI' AND A.LOCATION_NO = '13G02B' 

rollback